.TH CAS 1 "2005 március" "cas v0.5" "aMule segédprogramok"
.SH NÉV
cas \- c aMule statisztikák
.SH ÁTTEKINTÉS
.B cas
.RI [ OPCIÓK ]
.SH LEÍRÁS
.PP
    ___    _ _   ___    c aMule statisztikák
  /'___) /'_` )/',__)   írta Pedro de Oliveira
 ( (___ ( (_| |\\\__, \\   <falso@rdk.homeip.net>
 `\\____)`\\__,_)(____/   Verzió: 0.5
.P
A \fBcas\fR egy program az aMule online-aláírás fájl tartamlának megjelenítésére a képernyõn.
.SS OPCIÓK:
.TP
\fB\-o\fR
Online-aláírás képet készít.
.TP
\fB\-p\fR
HTML oldal a statisztikákkal és képpel.
.TP
\fB\-h\fR, \fB\-\-help\fR
Rövid használati útmutató.
.P
Opciók nélkül kiírja az online-aláírás fájl tartalmát az stdout-ra.
.SH FÁJLOK
~/.aMule/casrc
.br
stat.png
.br
tmp.html
.SH ÍRÓ
A \fBcas\fR-t Pedro de Oliveira <falso@rdk.homeip.net> készítette.
.SH HIBÁK JELENTÉSE
A hibákat kérjük vagy a fórumon (\fIhttp://forum.amule.org/\fR), vagy a hibakövetõben (\fIhttp://bugs.amule.org/\fR) jelentsék.
Hibákról kérjük ne írjanak levelet (e-mail-t) se a levelzési listára, se közvetlenül valamelyik fejlesztõnek.
.SH COPYRIGHT
Az aMule és az összes hozzá tartozó segédprogram a GNU General Public Licence védelme alatt áll.
.SH LÁSD MÉG
\fBamule\fR(1), \fBwxcas\fR(1)
.SH MAGYAR FORDÍTÁS
Dévai Tamás <gonosztopi@amule.org>
