.TH WXCAS 1 "January 2007" "wxCas" "aMule utilities"
.SH NAME
wxcas \- wx c aMule statistics
.SH SYNOPSIS
.B wxcas
.SH DESCRIPTION
.B wxcas
is a program for displaying the contents of your 
online signature file in a nice wx Window on your Desktop.
Based on Pedro de Oliveira's \fBcas\fR(1).

This program doesn't take any arguments.
.PP
The full documentation of wxcas can be downloaded from \fIhttp://download.berlios.de/amule/wxcas_user_manual.pdf\fR.
.SH AUTHOR
\fBwxcas\fR was written by ThePolish <thepolish@vipmail.ru>
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
\fBamule\fR(1), \fBcas\fR(1)
