.TH AMULEWEB 1 "March 2005" "aMule webserver v2.0.0" "aMule utilities"
.SH NAME
amuleweb \- aMule web server
.SH SYNOPSIS
.B amuleweb
.RB [ \-h " " \fI<host> ]
.RB [ \-p " " \fI<port> ]
.RB [ \-P " " \fI<pass> ]
.RB [ \-f " " \fI<path> ]
.RB [ \-q ]
.RB [ \-v ]
.RB [ \-l " " \fI<lang> ]
.RB [ \-w ]
.RB [ \-t " " \fI<name> ]
.RB [ \-s " " \fI<port> ]
.RB [ \-z ]
.RB [ \-Z ]
.RB [ \-A " " \fI<pass> ]
.RB [ \-G " " \fI<pass> ]
.RB [ \-a ]
.RB [ \-d ]
.RB [ \-L ]
.RB [ \-N ]
.PP
.B amuleweb
.RB [ \-f " " \fI<path> ]
.B \-\-create-config-from=\fI<path>
.PP
.B amuleweb
.RB [ \-\-help ]
.RB [ \-\-version ]
.PP
.B amuleweb \-\-amule\-config\-file=\fI<path>
.PP
.B amuleweb \-\-no\-php
.SH DESCRIPTION
\fBamuleweb\fR manages your access to amule through a webbrowser.
You can start amuleweb together with \fBamule\fR(1), or separately, any time later.
Options can be specified via command-line or via config-file.
Command-line options take precedence over config-file options.
.TP
\fB\-h\fR, \fB\-\-host\fR=\fI<host>\fR
Host where aMule is running (default: \fIlocalhost\fR).
\fI<host>\fR might be an IP address or a DNS name
.TP
\fB\-p\fR, \fB\-\-port\fR=\fI<port>\fR
aMule's port for External Connections, as set in Preferences->Remote Controls (default: \fI4712\fR)
.TP
\fB\-P\fR, \fB\-\-password\fR=\fI<passwd>\fR
External Connections password
.TP
\fB\-f\fR, \fB\-\-config\-file\fR=\fI<path>\fR
Use the given configuration file.
Default configuration file is \fI~/.aMule/remote.conf\fR
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Do not print any output to stdout.
You may want to use \fB\-q\fR to daemonize the webserver, i.e. running as '\fBamuleweb \-q &\fR'
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be verbose \- show also debug messages
.TP
\fB\-l\fR, \fB\-\-locale\fR=\fI<lang>\fR
Sets program locale (language).
See section \fBNOTES\fR for the description of the \fI<lang>\fR parameter.
.TP
\fB\-w\fR, \fB\-\-write\-config\fR
Write command line options to config file and exit
.TP
\fB\-\-create\-config\-from\fR=\fI<path>\fR
Create config file based upon \fI<path>\fR, which must point to a valid aMule config file, and then exit
.TP
\fB\-t\fR, \fB\-\-template\fR=\fI<name>\fR
Loads the template named \fI<name>\fR. See also the section
.B SKIN SUPPORT
.TP
\fB\-s\fR, \fB\-\-server\-port\fR=\fI<port>\fR
Webserver's HTTP port. This is the port you can point your browser to (default: \fI4711\fR)
.TP
\fB\-z\fR, \fB\-\-enable\-gzip\fR
Enable using gzip compression in HTTP traffic to save bandwidth
.TP
\fB\-Z\fR, \fB\-\-disable\-gzip\fR
Disable using gzip compression (this is the default)
.TP
\fB\-A\fR, \fB\-\-admin\-pass\fR=\fI<passwd>\fR
Full access password for webserver
.TP
\fB\-G\fR, \fB\-\-guest\-pass\fR=\fI<passwd>\fR
Guest password for webserver
.TP
\fB\-a\fR, \fB\-\-allow\-guest\fR
Allow guest access
.TP
\fB\-d\fR, \fB\-\-deny\-guest\fR
Deny guest access (default)
.TP
\fB\-L\fR, \fB\-\-load\-settings\fR
Load/save webserver settings from/to remote aMule.
This causes amuleweb to ignore command-line and config-file settings, and load them from aMule.
When saving preferences none will be written to the config file, but to aMule.
(Of course, this works only for those settings, that can be set in aMule's Preferences->Remote Controls)
.TP
\fB\-N\fR, \fB\-\-no\-script\-cache\fR
Recompile PHP pages on each request
.TP
\fB\-\-amule\-config\-file\fR=\fI<path>\fR
aMule config file path.
.B DO NOT USE DIRECTLY!
aMule uses this option when starting amuleweb at aMule startup.
This option causes all other command-line and config-file settings to be ignored, preferences to be read from the given config file, and also implies the \fB\-q \-L\fR options.
.TP
\fB\-\-help\fR
Display usage help information and exit
.TP
\fB\-\-version\fR
Output program version information and exit
.SH NOTES
.SS Paths
If you specify a file without giving an absolute path (i.e. just a plain filename, such as \fB\-\-path\fR=\fIremote.conf\fR), then this file is searched within the aMule configuration directory, \fI~/.aMule\fR.
.SS Languages
The \fI<lang>\fR parameter for the \fB\-l\fR option has the following form: \fIlang\fR[\fB_\fILANG\fR][\fB.\fIencoding\fR][\fB@\fImodifier\fR]
where \fIlang\fR is the primary language, \fILANG\fR is a sublanguage/territory, \fIencoding\fR is the character set to use and \fImodifier\fR
"allows the user to select a specific instance of localization data within a single category".
.PP
For example, the following strings are valid:
.br
fr
.br
fr_FR
.br
de_DE.iso88591
.br
de_DE@euro
.br
de_DE.iso88591@euro
.PP
Though all the above strings are accepted as valid language definitions, \fIencoding\fR and \fImodifier\fR are yet unused.
.PP
In addition to the format above, you can also specify full language names in English - so \fB\-l german\fR is also valid and is equal to \fB-l de_DE\fR.
.PP
When no locale is defined, either on command-line or in config file, system default language will be used.
.SH SKIN SUPPORT
\fBamuleweb\fR is capable of displaying information in different skins.
These skins are called templates, and you can make amuleweb load a specific template via the \fB\-t\fR command line option.
Templates are searched in two places: first in \fI~/.aMule/webserver/\fR and then in \fI$(pkgdatadir)/webserver/\fR 
(\fI$(pkgdatadir)\fR is the install location of architecture independent data, most likely something like /usr/share/amule).
Each template must be in a subdirectory of the template name, and this directory must contain all files the template needs.
The actual template filename must be aMule.tmpl.
.PP
For example, the default template (named 'default') is in webserver/default/, and this directory contains aMule.tmpl amongst a lot of image files.
.SH FILES
~/.aMule/remote.conf
.br
~/.aMule/webserver/
.br
\fI$(pkgdatadir)\fR/webserver/
.SH EXAMPLE
Typically amuleweb will be first run as:
.PP
\fBamuleweb\fR \fB\-h\fR \fIhostname\fR \fB\-p\fR \fIECport\fR \fB\-P\fR \fIECpassword\fR \fB\-s\fR \fIHTTPport\fR \fB\-A\fR \fIAdminPassword\fR \fB\-w\fR
.PP
or
.PP
\fBamuleweb\fR \fB\-\-create-config-from\fR=\fI/home/username/.aMule/amule.conf\fR
.PP
These will save settings to \fI$HOME/.aMule/remote.conf\fR, and later you only need to type:
.PP
.B amuleweb
.PP
Of course, you may specify any more or less options on the first example line, and you may also totally omit it.
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
\fBamule\fR(1), \fBamulecmd\fR(1)
