.TH AMULED 1
.SH NAME
amuled \- the all\-platform eMule p2p client \- daemon version
.SH SYNOPSIS
.B amuled
.RB [ \-v ]
.RB [ \-h ]
.RB [ \-i ]
.RB [ \-f ]
.RB [ \-\-config\-dir\=\<str\> ]
.RB [ \-d ]
.RB [ \-o ]
.SH BESCHREIBUNG
.TP
\fB\-v\fR, \fB\-\-version\fR
Zeigt die Versionsnummer an.
.TP
\fB\-h\fR, \fB\-\-help\fR
Zeigt diese Infos an.
.TP
\fB-i\fR, \fB\-\-enable\-stdin\fR
Schaltet stdin nicht ab.
.TP
\fB\-f\fR, \fB\-\-full\-daemon\fR
Geht in den Hintergrund
.TP
\fB\-\-config\-dir\=\<str\>\fR
Liest die Konfiguration aus dem angegebenen Verzeichnis anstatt aus dem Heimatverzeichnis.
.TP
\fB\-d\fR, \fB\-\-disable\-fatal\fR
Verarbeitet keine fatalen Fehler.
.TP
\fB-o\fR, \fB\-\-log\-stdout\fR
Gib log messages nach stdout.
.SH DATEIEN
~/.aMule/*
.br
~/.eMule
.SH PROBLEME BERICHTEN
Bitte berichte Fehler im Programm entweder im Forum (\fIhttp://forum.amule.org/\fR), oder in unserem Bugtracker (\fIhttp://bugs.amule.org/\fR).
Bitte berichte keine Fehler per E-Mail, auch nicht an unsere Mailingliste oder direkt an ein Teammitglied.
.SH COPYRIGHT
aMule und alle seine Tools stehen unter der GNU General Public License.
.SH SIEHE AUCH
\fBalcc\fR(1), \fBamule\fR(1), \fBamulecmd\fR(1), \fBamuleweb\fR(1), \fBcas\fR(1), \fBed2k\fR(1)
