.TH AMULED 1 "March 2005" "aMule Daemon v2.0.0" "aMule Daemon"
.SH NAME
amuled \- the all\-platform eMule p2p client \- daemonized version
.SH SYNOPSIS
.B amuled
.RB [ \-v ]
.RB [ \-h ]
.RB [ \-i ]
.RB [ \-f ]
.RB [ \-c " " \fI<dir> ]
.RB [ \-d ]
.RB [ \-o ]
.RB [ \-r ]

.SH DESCRIPTION
.TP
\fB\-v\fR, \fB\-\-version\fR
Displays the current version number.
.TP
\fB\-h\fR, \fB\-\-help\fR
Displays this information.
.TP
\fB-i\fR, \fB\-\-enable\-stdin\fR
Does not disable stdin.
.TP
\fB\-f\fR, \fB\-\-full\-daemon\fR
Fork to Background
.TP
\fB\-c\fR, \fB\-\-config\-dir\fR=\fI<dir>\fR
Read config from <dir> instead of home.
.TP
\fB\-d\fR, \fB\-\-disable\-fatal\fR
Does not handle fatal exception.
.TP
\fB-o\fR, \fB\-\-log\-stdout\fR
Print log messages to stdout.
.SH FILES
~/.aMule/*
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
\fBalcc\fR(1), \fBamule\fR(1), \fBamulecmd\fR(1), \fBamulegui\fR(1), \fBamuleweb\fR(1), \fBcas\fR(1), \fBed2k\fR(1)
