.TH AMULE 1 "2005 Martxoa" "aMule 2.0.0b" "aMule"
.SH IZENA
amule \- Plataforma orotarako eMule p2p bezeroa
.SH SYNOPSIS
.B amule
.RB [ \-v ]
.RB [ \-h ]
.RB [ \-i ]
.RB [ \-geometry " " \fI<geom> ]
.RB [ \-d ]
.RB [ \-o ]
.RB [ \-r ]
.SH AZALPENA
.TP
\fB\-v\fR, \fB\-\-version\fR
Bertsio zenbakia bistaratzen du.
.TP
\fB\-h\fR, \fB\-\-help\fR
Argibide hauek bistaratzen ditu.
.TP
\fB-i\fR, \fB\-\-enable\-stdin\fR
Ez irteera estandarra ezgaitu.
.TP
\fB\-geometry\fR \fI<geom>\fR
Aplikazioaren geometria ezarri.
\fI<geom>\fR-ek X11 aplikazioen formatu estanda berdina erabiltzen du:	[\fB=\fR][\fI<width>\fR{\fBxX\fR}\fI<height>\fR][{\fB+-\fR}\fI<xoffset>\fR{\fB+-\fR}\fI<yoffset>\fR]
.TP
\fB\-d\fR, \fB\-\-disable\-fatal\fR
Ez kudeatu salbuespen konponezinak.
.TP
\fB\-o\fR, \fB\-\-log\-stdout\fR
Erregistro mezuak irteera estandarrean inprimatu.
.TP
\fB\-r\fR, \fB\-\-reset\-config\fR
Konfigurazioan balio lehenetsian berrezarri.
\
.SH FITXATEGIAK
~/.aMule/*
.SH ZORRIEN BERRI EMATEN
Mesedez zorrien berri emateko gure foroa (\fIhttp://forum.amule.org/\fR), edo gure zorri kudeatzailea (\fIhttp://bugs.amule.org/\fR) erabili.
Mesedez ez eman zorrien berri epostaz, ez gure eposta zerrendan ez taldeko partaideei.
.SH COPYRIGHT
aMule eta inguruneko lanabes guztiak GNU Lizentzia Publiko Orokorraz banatzen dira.
.SH IKUSI ERE
\fBalc\fR(1), \fBalcc\fR(1), \fBamuled\fR(1), \fBamulecmd\fR(1), \fBamulegui\fR(1), \fBamuleweb\fR(1), \fBcas\fR(1), \fBed2k\fR(1), \fBwxcas\fR(1), \fBxas\fR(1)
