.TH AMULEWEBDLG 1
.SH NAME
amulewebDLG \- aMule web server \- GUI version
.SH SYNOPSIS
.B amulewebDLG
.RB [ \-h " " \fI<host> ]
.RB [ \-p " " \fI<port> ]
.RB [ \-P " " \fI<passwd> ]
.RB [ \-f " " \fI<path> ]
.RB [ \-q ]
.RB [ \-v ]
.RB [ \-w ]
.RB [ \-t " " \fI<name> ]
.RB [ \-s " " \fI<port> ]
.RB [ \-z ]
.RB [ \-Z ]
.RB [ \-A " " \fI<adminpass> ]
.RB [ \-G " " \fI<guestpass> ]
.RB [ \-a ]
.RB [ \-d ]
.RB [ \-L ]
.PP
.B amulewebDLG
.RB [ \-\-help ]
.RB [ \-\-version ]
.PP
.B amulewebDLG
.RB [ \-\-amule\-config\-file=\fI<path> ]
.SH BESCHREIBUNG
amuleweb ermoeglicht es die Verbindug zu aMule mittels eines Webbrowsers.
.PP
amulewebDLG ist genau dasselbe wie \fBamuleweb\fR(1), ausser das es eine nette(?) GUI Oberflaeche hat.
Fuer eine detaiert Beschreibung der Kommandozeilen Optionen und mehr Informationen siehe \fBamuleweb\fR(1).
.SH PROBLEME BERICHTEN
Bitte berichte Fehler im Programm entweder im Forum (\fIhttp://forum.amule.org/\fR), oder in unserem Bugtracker (\fIhttp://bugs.amule.org/\fR).
Bitte berichte keine Fehler per E-Mail, zu unserer Mailingliste oder direkt zu einem Teammitglied.
.SH COPYRIGHT
aMule und alle seine Tools stehen unter der GNU General Public License.
.SH SIEHE AUCH
\fBamule\fR(1), \fBamulecmd\fR(1), \fBamuleweb\fR(1)
