.TH AMULECMDDLG 1
.SH NAME
amulecmd \- Text-based program to control aMule, with GUI
.SH SYNOPSIS
.B amulecmdDLG
.RB [ \-h " " \fI<host> ]
.RB [ \-p " " \fI<port> ]
.RB [ \-P " " \fI<passwd> ]
.RB [ \-f " " \fI<path> ]
.RB [ \-q ]
.RB [ \-v ]
.RB [ \-w ]
.PP
.B amulecmdDLG
.RB [ \-\-help ]
.RB [ \-\-version ]
.SH DESCRIPTION
amulecmd is a text-based client to control aMule. Useful help can
be obtained when you launch the program.
.PP
amulecmdDLG is completely the same as \fBamulecmd\fR(1), except that it has a nice(?) GUI interface.
For a description of command-line parameters and for more information see \fBamulecmd\fR(1).
.SH NOTE
The GUI client does not accept the \fB\-c\fR command-line option.
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
\fBamule\fR(1), \fBamulecmd\fR(1), \fBamuleweb\fR(1)
