.TH ED2K "1" "January 2010" "aMule eD2k link parser v1.5.1" "aMule utilities"
.als B_untranslated B
.als RB_untranslated RB
.SH NAME
ed2k \- aMule eD2k link parser
.SH SYNOPSIS
.B_untranslated ed2k
.RB [ \-c " " \fI<path> ]
.RB [ \-t " " \fI<num> ]
.RB_untranslated [ \-e ]
.RB_untranslated [ \-l ]
.I <eD2k-link>

.B_untranslated ed2k
.RB_untranslated [ \-h ]

.B_untranslated ed2k
.RB_untranslated [ \-v ]
.SH DESCRIPTION
Sends the given \fI<eD2k-link>\fR to aMule, i.e. writes it to the file ~/.aMule/ED2KLinks, which will be checked by aMule every second for links.
.TP
\fB[ \-c\fR \fI<path>\fR, \fB\-\-config\-dir\fR=\fI<path>\fR \fB]\fR
Read config from \fI<path>\fR instead of home
.TP
\fB[ \-t\fR, \fB\-\-category\fR=\fI<num>\fR \fB]\fR
Set category for passed eD2k links to \fI<num>\fR
.TP
.B_untranslated [ \-e\fR, \fB\-\-emulecollection ]\fR
Loads all link found in the emulecollection given as \fI<ed2k-link>\fR
.TP
.B_untranslated [ \-l\fR, \fB\-\-list ]\fR
Lists all link found in the emulecollection given as \fI<ed2k-link>\fR
.TP
.B_untranslated [ \-h\fR, \fB\-\-help ]\fR
Prints a short usage description.
.TP
.B_untranslated [ \-v\fR, \fB\-\-version ]\fR
Displays the current version number.
.TP
\fB[ eD2k-link ]\fR
Adds an eD2k-link to the core.
.PP
The eD2k link to be added can be:
.RS 3
.IP \(bu 2
a file link (ed2k://|file|...), it will be added to the download queue;
.IP \(bu 2
a server link (ed2k://|server|...), it will be added to the server list;
.IP \(bu 2
a serverlist link, in which case all servers in the list will be added to the server list;
.IP \(bu 2
a magnet link;
.IP \(bu 2
an emulecollection file.
.RE

\fBThe order in which you give the parameters is important.\fR
You can give more than one link, and every link can have it's own params.
For example \fBed2k <link1> -t2 <link2>\fR will download \fI<link1>\fR in standard category and \fI<link2>\fR in category 2.
.SH FILES
~/.aMule/ED2KLinks
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
.B_untranslated amule\fR(1)
.SH AUTHOR
This manpage was written by Vollstrecker <amule@vollstreckernet.de>
