.TH ALCC "1" "January 2010" "aMule eD2k links calculator" "aMule utilities"
.als B_untranslated B
.als RB_untranslated RB
.SH NAME
alcc \- text based eD2k links calculator for aMule
.SH SYNOPSIS
.B_untranslated alcc
.RB_untranslated [ \-p ]
.RB_untranslated [ \-v ]
.I <inputfiles_list>

.B_untranslated alcc
.RB_untranslated [ \-h ]
.SH DESCRIPTION
Compute the eD2k links of all the input files given in the \fI<inputfiles_list>\fR (There can be one or more files).
.TP
.B_untranslated [ \-p\fR, \fB\-\-parthashes ]\fR
Compute and add part hashes to the computed eD2k links.
.TP
.B_untranslated [ \-h\fR, \fB\-\-help ]\fR
Prints a short usage description.
.TP
.B_untranslated [ \-v\fR, \fB\-\-verbose ]\fR
Be verbose \-
show also calculation steps.
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
.B_untranslated alc\fR(1), \fBamuled\fR(1), \fBamulecmd\fR(1), \fBamuleweb\fR(1), \fBcas\fR(1), \fBed2k\fR(1), \fBwxcas\fR(1), \fBxas\fR(1)
.SH AUTHOR
This manpage was written by Vollstrecker <amule@vollstreckernet.de>
