.TH ALCC "1" "2005 Martxoa" "aMule ED2k lotura sortzailea" "aMule lanabesak"
.SH IZENA
alcc \- testuan oinarrituriko aMule ED2k lotura sortzailea
.SH LABURPENA
.B alcc
.RB [ \-p ]
.RB [ \-v ]
.I <sarrerafitxategi_zerrenda>
.PP
.B alcc
.RB [ \-h ]
.SH AZALPENA
\fI<inputfiles_list>\fR-en emandako sarrera fitxategi guztien ED2K loturak kalkulatu (fixtategi bat edo gehiago izan 
daitezke).
.SS "Erabilera:"
.TP
\fB\-h, \-\-help\fR
Laguntza hau inprimatu.
.TP
\fB\-v, \-\-verbose\fR
Luze izan: kalkulu pausuak inprimatu.
.TP
\fB\-p, \-\-parthashes\fR
Kalkulatutako ED2k loturei zati egiaztapenak gehitu edo kalkulatu.
ZORRIEN BERRI EMATEN
Mesedez zorrien berri emateko gure foroa (\fIhttp://forum.amule.org/\fR), edo gure zorri kudeatzailea
(\fIhttp://bugs.amule.org/\fR) erabili.
Mesedez ez eman zorrien berri epostaz, ez gure eposta zerrendan ez taldeko partaideei.
.SH COPYRIGHT
aMule eta inguruneko lanabes guztiak GNU Lizentzia Publiko Orokorraz banatzen dira.
.SH IKUSI ERE
\fBalc\fR(1), \fBamuled\fR(1), \fBamulecmd\fR(1), \fBamuleweb\fR(1), \fBcas\fR(1), \fBed2k\fR(1), \fBwxcas\fR(1), \fBxas\fR(1)
