.TH CAS 1 "Marzo 2005" "cas v0.5" "Utilidades de aMule"
.SH NOMBRE
cas \- Estadísticas de aMule
.SH SINOPSIS
.B cas
.RI [ OPCIONES ]
.SH DESCRIPCIÓN
.PP
    ___    _ _   ___    Estadístics de aMule
  /'___) /'_` )/',__)   por Pedro de Oliveira
 ( (___ ( (_| |\\\__, \\   <falso@rdk.homeip.net>
 `\\____)`\\__,_)(____/   Versión 0.5
.P
\fBcas\fR es un programa que permite ver el contenido de la firma de aMule en tu consola de manera sencilla.
.SS OPCIONES:
.TP
\fB\-o\fR
Crea una imágen de la firma.
.TP
\fB\-p\fR
Crea una página HTML con las estadísticas y la imágen de la firma.
.TP
\fB\-h\fR, \fB\-\-help\fR
Printra una breve ayuda.
.P
Sin opciones, muestra en consola las estadísticas de la firma.
.SH ARCHIVOS
~/.aMule/casrc
.br
stat.png
.br
tmp.html
.SH AUTOR
\fBcas\fR ha sido escrito por Pedro de Oliveira <falso@rdk.homeip.net>
.SH BUGS
Si descubre bugs, por favor comuníquelos en (\fIhttp://forum.amule.org/\fR), o en nuestro bugtracker (\fIhttp://bugs.amule.org/\fR).
Por favor, no comunique bugs por e-mail, ni a nuestro maillist ni directamente a ningún miembro del equipo de aMule.
.SH COPYRIGHT
aMule, y todas las utilidades que con el vienen, se distribuyen bajo la licencia GPL.
.SH VER
\fBamule\fR(1), \fBwxcas\fR(1)
