.TH XAS 1 "January 2007" "xas v1.9" "aMule utilities"
.SH NAME
xas \- X\-Chat aMule Statistics
.SH SYNOPSIS
.B none
.SH DESCRIPTION
.B xas
is a plugin for xchat. For loading see your xchat documentation. After loading 
type /xas and it will send statistics to the channel you are in. These 
are taken from your Online Signature file.
For this to work, you must enable the "Online Signature" option in aMules preferences.

To enable it on every startup of xchat you can just run the script in /usr/bin/autstart-xas.
.SH AUTHOR
\fBxas\fR was originally written by niet
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
\fBamule\fR(1)
