.TH XAS 1 "January 2010" "xas v1.9" "aMule utilities"
.als B_untranslated B
.SH NAME
xas \- X\-Chat aMule Statistics
.SH SYNOPSIS
.B none
.SH DESCRIPTION
\fBxas\fR is a plugin for xchat. For loading see your xchat documentation. After loading 
type /xas and it will send statistics to the channel you are in. These 
are taken from your Online Signature file.
For this to work, you must enable the "Online Signature" option in aMule's preferences.

To enable it on every startup of xchat you can just run the autstart-xas script (in /usr/bin if you installed with \-\-prefix=/usr).

\fBxas\fR was originally written by niet
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
.B_untranslated amule\fR(1)
.SH AUTHOR
This manpage was written by Vollstrecker <amule@vollstreckernet.de>
