.TH XAS 1 "2005 március" "xas" "aMule segédprogramok"
.SH NÉV
xas \- X\-Chat aMule Statisztikák
.SH ÁTTEKINTÉS
.B nincs
.SH LEÍRÁS
A \fBxas\fR egy xchat plugin.
.
A betöltéséhez olvasd el az xchat dokumentációját.
.
Betöltés után a /xas parancs az aMule statisztikáit kiírja az aktuális csatornára.
.
Ezek az Online Aláírás fájlból kerülnek kiolvasásra.
.SH ÍRÓ
A \fBxas\fR-t eredetileg niet írta.
.SH HIBÁK JELENTÉSE
A hibákat kérjük vagy a fórumon (\fIhttp://forum.amule.org/\fR), vagy a hibakövetõben (\fIhttp://bugs.amule.org/\fR) jelentsék.
Hibákról kérjük ne írjanak levelet (e-mail-t) se a levelzési listára, se közvetlenül valamelyik fejlesztõnek.
.SH COPYRIGHT
Az aMule és az összes hozzá tartozó segédprogram a GNU General Public Licence védelme alatt áll.
.SH LÁSD MÉG
\fBamule\fR(1)
.SH MAGYAR FORDÍTÁS
Dévai Tamás <gonosztopi@amule.org>
