.TH WXCAS 1 "March 2005" "wxCas" "aMule utilities"
.SH NAME
wxcas \- wx c aMule statistics
.SH SYNTAX
.B wxcas
.SH BESCHREIBUNG
.B wxcas
wxcas ist ein GUI Tool welches den Inhalt der Online-Signartur auf deinem Bildschirm ausgibt.
Zusätzlich hat man noch einige FTP funktionen um die Imagedatei ins Internet zu laden.
Dieses Tool basiert auf dem Programm \fBcas\fR(1) von Pedro de Oliveira
.PP
Die komplette Dokumentation von wxcas kann man hier bekommen \fIhttp://download.berlios.de/amule/wxcas_user_manual.pdf\fR.
.SH AUTHOR
wxcas wurde geschrieben von ThePolish <thepolish@vipmail.ru>
.SH PROBLEME BERICHTEN
Bitte berichte Fehler im Programm entweder im Forum (\fIhttp://forum.amule.org/\fR), oder in unserem Bugtracker (\fIhttp://bugs.amule.org/\fR).
Bitte berichte keine Fehler per E-Mail, auch nicht an unsere Mailingliste oder direkt an ein Teammitglied.
.SH COPYRIGHT
aMule und alle seine Tools stehen unter der GNU General Public License.
.SH SIEHE AUCH
\fBamule\fR(1), \fBcas\fR(1)
