.TH WXCAS 1 "2005 Martxoa" "wxCas" "aMule utilities"
.SH IZENA
wxcas \- wx c aMule statistikak
.SH LABURPENA
.B wxcas
.SH AZALPENA
.B wxcas
zure aMule lineako sinadura fitxategiarne edukiak zure idazmahaieko wx leiho polit batetan bistaratzeko programa da.
Pedro de Oliveira\-ren \fBcas\fR(1)-en oinarriturik.
.PP
wxcas-en dokumentazio osoa \fIhttp://download.berlios.de/amule/wxcas_user_manual.pdf\fR-en deskarga daiteke.
.SH EGILEA
\fBwxcas\fR ThePolish-ek <thepolish@vipmail.ru> idatzia da.
.SH ZORRIEN BERRI EMATEN
Mesedez zorrien berri emateko gure foroa (\fIhttp://forum.amule.org/\fR), edo gure zorri kudeatzailea
(\fIhttp://bugs.amule.org/\fR) erabili.
Mesedez ez eman zorrien berri epostaz, ez gure eposta zerrendan ez taldeko partaideei.
.SH COPYRIGHT
aMule eta inguruneko lanabes guztiak GNU Lizentzia Publiko Orokorraz banatzen dira.
.SH IKUSI ERE
\fBamule\fR(1), \fBcas\fR(1)
