.TH WXCAS 1 "2005 március" "wxCas" "aMule segédprogramok"
.SH NÉV
wxcas \- wx c aMule statisztikák
.SH ÁTTEKINTÉS
.B wxcas
.SH LEÍRÁS
A \fBwxcas\fR az aMule online-aláírás fájljának tartalmát jeleníti meg egy szép ablakban.
Készült a Pedro de Oliveira által készített \fBcas\fR(1) program alapján.
.PP
A \fBwxcas\fR teljes dokumentációja letölthetõ a \fIhttp://download.berlios.de/amule/wxcas_user_manual.pdf\fR címrõl.
.SH ÍRÓ
A \fBwxcas\fR-t ThePolish <thepolish@vipmail.ru> írta.
.SH HIBÁK JELENTÉSE
A hibákat kérjük vagy a fórumon (\fIhttp://forum.amule.org/\fR), vagy a hibakövetõben (\fIhttp://bugs.amule.org/\fR) jelentsék.
Hibákról kérjük ne írjanak levelet (e-mail-t) se a levelzési listára, se közvetlenül valamelyik fejlesztõnek.
.SH COPYRIGHT
Az aMule és az összes hozzá tartozó segédprogram a GNU General Public Licence védelme alatt áll.
.SH LÁSD MÉG
\fBamule\fR(1), \fBcas\fR(1)
.SH MAGYAR FORDÍTÁS
Dévai Tamás <gonosztopi@amule.org>
