#!/usr/bin/python
#
# This file is part of the aMule project.
#
# Copyright (c) 2003-2005 aMule Project ( admin@amule.org / http://www.amule.org )
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# Usage:
#  svn log ... | logfilter <nick> [<nick2> [<nickn> ...]]

import sys

line = sys.stdin.readline()
while line:
	if not line.strip().startswith("-"):
		foundNick = False
		for user in sys.argv[1:]:
			if user == line.lower().split()[2]:
				foundNick = True
				break

		if foundNick:
			print ("-" * 72)
			print line.strip()
	
		# Check for -q
		if line.count("|") > 2:
			lineCount = int(line.split("|")[-1].split()[0])
			line = sys.stdin.readline()

			if foundNick: print line.rstrip()
				
			if line.strip() == "Changed paths:":
				line = sys.stdin.readline()
				while line.strip():
					if foundNick: print line.rstrip()
					line = sys.stdin.readline()

				if foundNick: print
			
			for i in range(lineCount):
				line = sys.stdin.readline()
				if foundNick: print line.rstrip()

	line = sys.stdin.readline()
