.TH ALC 1 "March 2005" "aLinkCreator" "aMule utilities"
.SH NAME
aLinkCreator \- the aMule ED2k link creator
.SH SYNOPSIS
.B alc
.SH DESCRIPTION
\fBalc\fR ist ein Grafisches Tool zum erstellen von ED2K Links für jede Datei auf dem Computer.
.SH PROBLEME BERICHTEN
Bitte berichte Fehler im Programm entweder im Forum (\fIhttp://forum.amule.org/\fR), oder in unserem Bugtracker (\fIhttp://bugs.amule.org/\fR).
Bitte berichte keine Fehler per E-Mail, zu unserer Mailingliste oder direkt zu einem Teammitglied.
.SH COPYRIGHT
aMule und alle seine Tools stehen unter der GNU General Public License.
.SH SIEHE AUCH
\fBalcc\fR(1), \fBamule\fR(1)
