<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$text["dayabbr"]	= "e";
$text["hourabbr"]	= "h";
$text["minabbr"]	= "m";
$text["secabbr"]	= "s";
$text["runtimemsg"]	= "martxan dago";
$text["norunmsg"]	= "ez dago martxan";
$text["connmsg"]	= "Konektatzen ari da";
$text["highidmsg"]	= "sarean dago (id altua)";
$text["lowidmsg"]	= "sarean dago (id baxua)";
$text["offrunmsg"]	= "ez dago sarean";
$text["amulerun"]	= "(aMule abiarazirik)";
$text["amulenorun"]	= "(aMule ez dago abiarazirik)";
$text["sharedfiles"]	= "Partekatutako Fitxategiak";

// try to keep these next three short, otherwise the signature
// image will look messy
$text["na"]		= "N/A";
$text["rx"]		= "RX";
$text["tx"]		= "TX";

$text["queuedclients"]	= "Bezero ilara";
$text["transrate"]	= "kB/s";
$text["gigabytes"]	= "GB";
$text["client"]		= "Bezero";
$text["status"]		= "Egoera";
$text["nick"]		= "Izenordea";
$text["localtime"]	= "Ordu lokala";
$text["rxspeed"]	= "Jeitxiera abiadura";
$text["txspeed"]	= "Igoera abiadura";
$text["rxtotal"]	= "Jeitxiera guztira";
$text["txtotal"]	= "Igoera guztira";
$text["osversion"]	= "SE bertsioa";
$text["hostuptime"]	= "Ostalaria abiarazitako denbora";
$text["servername"]	= "Zerbitzari izena";
$text["serveraddr"]	= "Zerbitzari helbidea:ataka";
$text["ed2klink"]	= "ED2K Esteka";
$text["general"]	= "Nagusia";
$text["server"]		= "Zerbitzaria";
$text["signature"]	= "Sinadura";
$text["connecting"]	= "Komektatzen";
$text["online"]		= "Sarean";
$text["offline"]	= "Sarez kampo";
$text["language"]	= "Hizkuntza";
$text["submit"]		= "Bidali";

$text["sigfileerr"]	= "Couldn't open signature file";
$text["baseimgerr"]	= "Cannot find base image";
$text["iconerr"]	= "Cannot find one or more icons";

?>
