<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$text["dayabbr"]	= "d";
$text["hourabbr"]	= "h";
$text["minabbr"]	= "m";
$text["secabbr"]	= "s";
$text["runtimemsg"]	= "uruchomiony od";
$text["norunmsg"]	= "jest not running";
$text["highidmsg"]	= "jest online (wysokie id)";
$text["lowidmsg"]	= "jest online (niskie id)";
$text["offrunmsg"]	= "jest offline";
$text["amulerun"]	= "(aMule uruchomiony)";
$text["amulenorun"]	= "(aMule nie uruchomiony)";
$text["sharedfiles"]	= "Udost&#281;pnione pliki";

// try to keep these next three short, otherwise the signature
// image will look messy
$text["na"]		= "N/A";
$text["rx"]		= "RX";
$text["tx"]		= "TX";

$text["queuedclients"]	= "Klient&#243;w w kolejce";
$text["transrate"]	= "kB/s";
$text["gigabytes"]	= "GB";
$text["client"]		= "Klient";
$text["status"]		= "Status";
$text["nick"]		= "Ksywa";
$text["localtime"]	= "Czas lokalny";
$text["rxspeed"]	= "Pr&#281;dko&#347;&#263; RX";
$text["txspeed"]	= "Pr&#281;dko&#347;&#263; TX";
$text["rxtotal"]	= "Razem RX";
$text["txtotal"]	= "Razem TX";
$text["osversion"]	= "Wersja OS";
$text["hostuptime"]	= "Uptime hosta";
$text["servername"]	= "Nazwa serwera";
$text["serveraddr"]	= "adres:port serwera";
$text["ed2klink"]	= "link ED2K";
$text["general"]	= "Og&#243;lne";
$text["server"]		= "Serwer";
$text["signature"]	= "Podpis";
$text["online"]		= "Online";
$text["offline"]	= "Offline";
$text["language"]	= "J&#281;zyk";
$text["submit"]		= "Zatwierd&#378;";

$text["sigfileerr"]	= "Nie mog&#281; otworzy&#263; pliku podpisu";
$text["baseimgerr"]	= "Nie znalaz&#322;em obrazka";
$text["iconerr"]	= "Nie znalaz&#322;em jednej lub wi&#281;cej ikon";

?>
