.TH AMULE 1
.SH NAME
cas
.SH SYNTAX
.B cas
.SH "Beschreibung"
.B cas
wx c aMule statistics ist ein Programm, das den Inhalt deiner 
Online-Signatur-Datei in einem hübschen wx-Fenster auf deinem Desktop ausgibt.
.PP
Die ManPage wurde für Debian GNU/Linux geschrieben, da das 
Originalprogramm keine enthält.

.SH AUTHOR
wxcas wurde geschrieben von ThePolish <thepolish@vipmail.ru>
Diese ManPage wurde für Debian geschrieben von Vollstrecker <amule@vollstreckernet.de> 

