.TH AMULE 1 "2005 március" "aMule v2.0.0" "aMule"
.SH NÉV
amule \- a "minden\-platform" eMule p2p kliens
.SH ÁTTEKINTÉS
.B amule
.RB [ \-v ]
.RB [ \-h ]
.RB [ \-i ]
.RB [ \-geometry " " \fI<geom> ]
.RB [ \-d ]
.RB [ \-o ]
.SH LEÍRÁS
.TP
\fB\-v\fR, \fB\-\-version\fR
Megjeleníti a verzió információt.
.TP
\fB\-h\fR, \fB\-\-help\fR
Ezt a súgót jeleníti meg.
.TP
\fB-i\fR, \fB\-\-enable\-stdin\fR
Nem zárja le a szabvány bemenetet (stdin).
.TP
\fB\-geometry\fR \fI<geom>\fR
Beállítja az alkalmazás geometriáját.
A \fI<geom>\fR paraméte ugyanazt a formátumot használja, mint a többi X11 alkalmazás: [\fB=\fR][\fI<szélesség>\fR{\fBxX\fR}\fI<magasság>\fR][{\fB+-\fR}\fI<xpozíció>\fR{\fB+-\fR}\fI<ypozíció>\fR]
.TP
\fB\-d\fR, \fB\-\-disable\-fatal\fR
Nem kezeli a végzetes kivételeket.
.TP
\fB-o\fR, \fB\-\-log\-stdout\fR
A szabvány kimenetre írja a napló üzeneteket.
.SH FÁJLOK
~/.aMule/*
.SH HIBÁK JELENTÉSE
A hibákat kérjük vagy a fórumon (\fIhttp://forum.amule.org/\fR), vagy a hibakövetõben (\fIhttp://bugs.amule.org/\fR) jelentsék.
Hibákról kérjük ne írjanak levelet (e-mail-t) se a levelzési listára, se közvetlenül valamelyik fejlesztõnek.
.SH COPYRIGHT
Az aMule és az összes hozzá tartozó segédprogram a GNU General Public Licence védelme alatt áll.
.SH LÁSD MÉG
\fBalc\fR(1), \fBalcc\fR(1), \fBamuled\fR(1), \fBamulecmd\fR(1), \fBamulegui\fR(1), \fBamuleweb\fR(1), \fBcas\fR(1), \fBed2k\fR(1), \fBwxcas\fR(1), \fBxas\fR(1)
.SH MAGYAR FORDÍTÁS
Dévai Tamás <gonosztopi@amule.org>
