<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$text["dayabbr"]	= "d";
$text["hourabbr"]	= "h";
$text["minabbr"]	= "m";
$text["secabbr"]	= "s";
$text["runtimemsg"]	= "est&#224; funcionant desde fa";
$text["norunmsg"]	= "no est&#224; funcionant";
$text["connmsg"]	= "s'est&#224; connectant";
$text["highidmsg"]	= "est&#224; connectat (id alta)";
$text["lowidmsg"]	= "est&#224; connectat (id baixa)";
$text["offrunmsg"]	= "est&#224; desconnectat";
$text["amulerun"]	= "(aMule executat)";
$text["amulenorun"]	= "(aMule parat)";
$text["sharedfiles"]	= "Fitxers compartits";

// try to keep these next three short, otherwise the signature
// image will look messy
$text["na"]		= "N/D";
$text["rx"]		= "RX";
$text["tx"]		= "TX";

$text["queuedclients"]	= "Clients a la Cua";
$text["transrate"]	= "kB/s";
$text["gigabytes"]	= "GB";
$text["client"]		= "Client";
$text["status"]		= "Estat";
$text["nick"]		= "Sobrenom";
$text["localtime"]	= "Hora local";
$text["rxspeed"]	= "velocitat RX";
$text["txspeed"]	= "velocitat TX";
$text["rxtotal"]	= "RX total";
$text["txtotal"]	= "TX total";
$text["osversion"]	= "versi&#115; del SO";
$text["hostuptime"]	= "Temps d'execussi&#115; del PC";
$text["servername"]	= "Nom del Servidor";
$text["serveraddr"]	= "adre&#231;a:port del Servidor";
$text["ed2klink"]	= "enlla&#231; ED2K";
$text["general"]	= "General";
$text["server"]		= "Servidor";
$text["signature"]	= "Signatura";
$text["connecting"]	= "Connectant";
$text["online"]		= "Connectat";
$text["offline"]	= "Desconnectat";
$text["language"]	= "Idioma";
$text["submit"]		= "Trametre";

$text["sigfileerr"]	= "No s'ha pogut obrir el fitxer de la Signatura";
$text["baseimgerr"]	= "No es troba l'imatge base";
$text["iconerr"]	= "No es troben un o m&#233;s icones";

?>
