<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$text["dayabbr"]	= "T";
$text["hourabbr"]	= "S";
$text["minabbr"]	= "m";
$text["secabbr"]	= "s";
$text["runtimemsg"]	= "l&#228;uft seit";
$text["norunmsg"]	= "l&#228;uft nicht";
$text["connmsg"]	= "verbindet gerade";
$text["highidmsg"]	= "ist online (high id)";
$text["lowidmsg"]	= "ist online (low id)";
$text["offrunmsg"]	= "ist offline";
$text["amulerun"]	= "(aMule l&#228;uft)";
$text["amulenorun"]	= "(aMule l&#228;uft nicht)";
$text["sharedfiles"]	= "Freigegebene Dateien";
$text["na"]		= "N/A";
$text["rx"]		= "Down";
$text["tx"]		= "Up";
$text["queuedclients"]	= "Clients in Warteliste";
$text["transrate"]	= "kB/s";
$text["gigabytes"]	= "GB";
$text["client"]		= "Client";
$text["status"]		= "Status";
$text["nick"]		= "Nick";
$text["localtime"]	= "Lokale Zeit";
$text["rxspeed"]	= "Download";
$text["txspeed"]	= "Upload";
$text["rxtotal"]	= "Download gesamt";
$text["txtotal"]	= "Upload gesamt";
$text["osversion"]	= "Betriebssystem";
$text["hostuptime"]	= "Host uptime";
$text["servername"]	= "Servername";
$text["serveraddr"]	= "Server Addresse:Port";
$text["ed2klink"]	= "ED2K Link";
$text["general"]	= "&#220;bersicht";
$text["server"]		= "Server";
$text["signature"]	= "Signatur";
$text["connecting"]	= "Verbinden";
$text["online"]		= "Online";
$text["offline"]	= "Offline";
$text["language"]	= "Sprache";
$text["submit"]		= "&#220;bernehmen";

$text["sigfileerr"]	= "Konnte Signaturdatei nicht &#246;ffnen (Couldn't open signature file)";
$text["baseimgerr"]	= "Kann Basis-Bild nicht finden (Cannot find base image)";
$text["iconerr"]	= "Kann eines oder mehrere Icons nicht finden (Cannot find one or more icons)";

?>
