<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$text["dayabbr"]	= " d";
$text["hourabbr"]	= " h";
$text["minabbr"]	= " min";
$text["secabbr"]	= " s";
$text["runtimemsg"]	= "on ollut p&#228;&#228;ll&#228;";
$text["norunmsg"]	= "ei ole p&#228;&#228;ll&#228;";
$text["highidmsg"]	= "on verkossa (korkea tunnus)";
$text["lowidmsg"]	= "on verkossa (matala tunnus)";
$text["offrunmsg"]	= "ei ole verkossa";
$text["amulerun"]	= "(aMule on p&#228;&#228;ll&#228;)";
$text["amulenorun"]	= "(aMule ei ole p&#228;&#228;ll&#228;)";
$text["sharedfiles"]	= "Jaettuja tiedostoja";
$text["na"]		= "-";
$text["rx"]		= "Sis&#228;&#228;n";
$text["tx"]		= "Ulos";
$text["queuedclients"]	= "Jonon pituus";
$text["transrate"]	= " KiB/s";
$text["gigabytes"]	= " GiB";
$text["client"]		= "Ohjelma";
$text["status"]		= "Tila";
$text["nick"]		= "Nimi";
$text["localtime"]	= "Paikallinen aika";
$text["rxspeed"]	= "Latausnopeus";
$text["txspeed"]	= "L&#228;hetysnopeus";
$text["rxtotal"]	= "Ladattu";
$text["txtotal"]	= "L&#228;hetetty";
$text["osversion"]	= "K&#228;ytt&#246j&#228;rjestelm&#228;";
$text["hostuptime"]	= "P&#228;&#228;ll&#228;oloaika";
$text["servername"]	= "Palvelimen nimi";
$text["serveraddr"]	= "Palvelimen osoite";
$text["ed2klink"]	= "ed2k-linkki";
$text["general"]	= "Yleiset";
$text["server"]		= "Palvelin";
$text["signature"]	= "Tilastokuva";
$text["online"]		= "On verkossa";
$text["offline"]	= "Ei ole verkossa";
$text["language"]	= "Kieli";
$text["submit"]		= "Valitse";

$text["sigfileerr"]	= "Tilastokuvaa ei voi avata";
$text["baseimgerr"]	= "Peruskuvaa ei l&#246ydy";
$text["iconerr"]	= "Yht&#228; tai useampaa kuvaketta ei l&#246ydy";

?>
