<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 **
 * Portuguese Brazilian pt_BR language by IgoR <igor.spy@gmx.net>
 * thanks fly out to: CapEnt ;)
 **
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// if you are translating this file, please replace all special characters with
// html unicode entities (&#nnn;). It's not always necessary, but ensures that
// there are minimal problems displaying the text in all browsers.

$text["dayabbr"]	= "d";
$text["hourabbr"]	= "h";
$text["minabbr"]	= "m";
$text["secabbr"]	= "s";
$text["runtimemsg"]	= "em execu&#231;&#227;o por"; // execução
$text["norunmsg"]	= "n&atilde;o est&#225; ativo"; // está
$text["connmsg"]	= "conectando";
$text["highidmsg"]	= "est&#225; online (HiGH iD)"; // está
$text["lowidmsg"]	= "est&#225; online (LOW iD)"; // está
$text["offrunmsg"]	= "est&#225; offline"; // está
$text["amulerun"]	= "(aMule rodando)";
$text["amulenorun"]	= "(aMule parado)";
$text["sharedfiles"]	= "Shared files";

// try to keep these next three short, otherwise the signature
// image will look messy
$text["na"]		= "N/A";
$text["rx"]		= "RX";
$text["tx"]		= "TX";

$text["queuedclients"]	= "Clientes na espera";
$text["transrate"]	= "kB/s";
$text["gigabytes"]	= "GB";
$text["client"]		= "Cliente";
$text["status"]		= "Status";
$text["nick"]		= "Nick";
$text["localtime"]	= "Hora local";
$text["rxspeed"]	= "RX speed";
$text["txspeed"]	= "TX speed";
$text["rxtotal"]	= "RX total";
$text["txtotal"]	= "TX total";
$text["osversion"]	= "Versão de OS";
$text["hostuptime"]	= "uptime host";
$text["servername"]	= "Nome do servidor";
$text["serveraddr"]	= "servidor.endere&#231;o:porta"; // endereço
$text["ed2klink"]	= "Link ED2K";
$text["general"]	= "General";
$text["server"]		= "Servidor";
$text["signature"]	= "Assinatura";
$text["connecting"]	= "Conectando";
$text["online"]		= "Online";
$text["offline"]	= "Offline";
$text["language"]	= "Lingua";
$text["submit"]		= "Enviar";

$text["sigfileerr"]	= "Erro ao abrir o arquivo de assinatura";
$text["baseimgerr"]	= "N&#227;o foi encontrado a imagem da base"; // Não
$text["iconerr"]	= "N&#227;o foi encontrado icones"; // Não

?>
