.TH ALC 1 "Marzo 2005" "aLinkCreator" "Utilidades de aMule"
.SH NOMBRE
aLinkCreator \- Creador de enlaces eD2k de aMule
.SH SINOPSIS
.B alc
.SH DESCRIPCIÓN
\fBalc\fR es una utilidad gráfica para crear enlaces eD2k de cualquier archivo.
.SH BUGS
Si descubre bugs, por favor comuníquelos en (\fIhttp://forum.amule.org/\fR), o en nuestro bugtracker (\fIhttp://bugs.amule.org/\fR).
Por favor, no comunique bugs por e-mail, ni a nuestro maillist ni directamente a ningún miembro del equipo de aMule.
.SH COPYRIGHT
aMule, y todas las utilidades que con el vienen, se distribuyen bajo la licencia GPL.
.SH VER
\fBalcc\fR(1), \fBamule\fR(1)
