.TH ALCC 1 "March 2005" "aLinkCreator" "aMule utilities"
.SH NAME
aLinkCreator \- the aMule ED2k link creator
.SH SYNOPSIS
.B alcc
.RB [ \-h ]
.RB [ \-v ]
.RB [ \-p ]
.I zu berechnende Dateien...
.SH BESCHREIBUNG
\fBalcc\fR ist ein Kommandozeilen Tool zum Erstellen von ED2K Links für jede Datei auf dem Computer.
.TP
\fB\-h\fR, \fB\-\-help\fR
Zeigt diese Hilfe.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Gibt zusätliche Informationen.
.TP
\fB\-p\fR, \fB\-\-parthashes\fR
Hängt Part-Hashes an den ED2K Link.
.SH PROBLEME BERICHTEN
Bitte berichte Fehler im Programm entweder im Forum (\fIhttp://forum.amule.org/\fR), oder in unserem Bugtracker (\fIhttp://bugs.amule.org/\fR).
Bitte berichte keine Fehler per E-Mail, auch nicht an unsere Mailingliste oder direkt an ein Teammitglied.
.SH COPYRIGHT
aMule und alle seine Tools stehen unter der GNU General Public License.
.SH SIEHE AUCH
\fBalc\fR(1), \fBamule\fR(1)
