.TH ALCC 1 "Marzo 2005" "aLinkCreator" "Utilidades de aMule"
.SH NOMBRE
aLinkCreator \- Creador de enlaces eD2k de aMule
.SH SINOPSIS
.B alcc
.RB [ \-h ]
.RB [ \-v ]
.RB [ \-p ]
.I archivos...
.SH DESCRIPCIÓN
\fBalcc\fR es una utilidad en modo comando para crear enlaces eD2k de cualquier archivo.
.TP
\fB\-h\fR, \fB\-\-help\fR
Muestra ayuda del modo de uso.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Mostrar información adicional.
.TP
\fB\-p\fR, \fB\-\-parthashes\fR
Añadir part-hashes a los enlaces eD2k.
.SH BUGS
Si descubre bugs, por favor comuníquelos en (\fIhttp://forum.amule.org/\fR), o en nuestro bugtracker (\fIhttp://bugs.amule.org/\fR).
Por favor, no comunique bugs por e-mail, ni a nuestro maillist ni directamente a ningún miembro del equipo de aMule.
.SH COPYRIGHT
aMule, y todas las utilidades que con el vienen, se distribuyen bajo la licencia GPL.
.SH VER
\fBalc\fR(1), \fBamule\fR(1)
