.TH AMULED 1 "Marzo 2005" "aMule Daemon v2.0.0" "Demonio aMule"
.SH NOMBRE
amuled \- Cliente P2P clon de eMule multi-plataforma \- versión demonio
.SH SINOPSIS
.B amuled
.RB [ \-v ]
.RB [ \-h ]
.RB [ \-i ]
.RB [ \-d ]
.RB [ \-o ]
.SH DESCRIPCIÓN
.TP
\fB\-v\fR, \fB\-\-version\fR
Muestra la versión del programa.
.TP
\fB\-h\fR, \fB\-\-help\fR
Muestra esta información.
.TP
\fB-i\fR, \fB\-\-enable\-stdin\fR
Deja activa la entrada estándar.
.TP
\fB\-d\fR, \fB\-\-disable\-fatal\fR
Ignpra las señales "Fatal exception".
.TP
\fB-o\fR, \fB\-\-log\-stdout\fR
Muestra los mensajes de log en la consola.
.SH ARHIVOS
~/.aMule/*
.SH BUGS
Si descubre bugs, por favor comuníquelos en (\fIhttp://forum.amule.org/\fR), o en nuestro bugtracker (\fIhttp://bugs.amule.org/\fR).
Por favor, no comunique bugs por e-mail, ni a nuestro maillist ni directamente a ningún miembro del equipo de aMule.
.SH COPYRIGHT
aMule, y todas las utilidades que con el vienen, se distribuyen bajo la licencia GPL.
.SH VER
\fBalcc\fR(1), \fBamule\fR(1), \fBamulecmd\fR(1), \fBamuleweb\fR(1), \fBcas\fR(1), \fBed2k\fR(1)
