//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: muuli.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_muuli_H__
#define __WDR_muuli_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "muuli_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

extern wxSizer *s_dlgcnt;
extern wxSizer *contentSizer;
extern wxSizer *s_fed2klh;
#define ID_BUTTON_FAST 10000
#define ID_STATICBITMAP 10001
wxSizer *muleDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_SRV_SPLITTER 10002
wxSizer *serverListDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

extern wxSizer *s_searchsizer;
#define IDC_SEARCHNAME 10003
#define ID_SEARCHTYPE 10004
#define IDC_EXTENDEDSEARCHCHECK 10005
#define IDC_FILTERCHECK 10006
extern wxSizer *s_extendedsizer;
#define IDC_TypeSearch 10007
#define ID_AUTOCATASSIGN 10008
#define IDC_EDITSEARCHEXTENSION 10009
#define IDC_SPINSEARCHMIN 10010
#define IDC_SEARCHMINSIZE 10011
#define IDC_SPINSEARCHMAX 10012
#define IDC_SEARCHMAXSIZE 10013
#define IDC_SPINSEARCHAVAIBILITY 10014
extern wxSizer *s_filtersizer;
#define ID_FILTER_TEXT 10015
#define ID_FILTER 10016
#define ID_FILTER_INVERT 10017
#define ID_FILTER_KNOWN 10018
#define IDC_STARTS 10019
#define IDC_SEARCHMORE 10020
#define IDC_CANCELS 10021
#define IDC_SDOWNLOAD 10022
#define IDC_SEARCH_RESET 10023
#define IDC_CLEAR_RESULTS 10024
#define ID_NOTEBOOK 10025
#define ID_SEARCHPROGRESS 10026
wxSizer *searchDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_BTNCLRCOMPL 10027
#define ID_CATEGORIES 10028
#define ID_DLOADLIST 10029
wxSizer *transferTopPane( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

extern wxSizer *s_clientlistHeader;
#define ID_CLIENTTOGGLE 10030
#define ID_BTNSWITCHUP 10031
#define ID_CLIENTCOUNT 10032
#define ID_CLIENTLIST 10033
wxSizer *transferBottomPane( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_FRIENDLIST 10034
#define IDC_CHATSELECTOR 10035
#define IDC_CMESSAGE 10036
#define IDC_CSEND 10037
#define IDC_CCLOSE 10038
wxSizer *messagePage( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_FNAME 10039
#define IDC_METFILE 10040
#define IDC_FHASH 10041
#define IDC_FSIZE 10042
#define IDC_PFSTATUS 10043
#define IDC_LASTSEENCOMPL 10044
#define IDC_SOURCECOUNT 10045
#define IDC_SOURCECOUNT2 10046
#define IDC_PARTCOUNT 10047
#define IDC_PARTAVAILABLE 10048
#define IDC_DATARATE 10049
#define IDC_DLACTIVETIME 10050
#define IDC_TRANSFERRED 10051
#define IDC_COMPLSIZE 10052
#define IDC_PROCCOMPL 10053
#define IDC_FD_STATS1 10054
#define IDC_FD_STATS2 10055
#define IDC_FD_STATS3 10056
#define IDC_LISTCTRLFILENAMES 10057
#define IDC_TAKEOVER 10058
#define IDC_CMTBT 10059
#define IDC_BUTTONSTRIP 10060
#define IDC_FILENAME 10061
#define IDC_APPLY 10062
#define IDC_APPLY_AND_CLOSE 10063
#define ID_CLOSEWNDFD 5100
wxSizer *fileDetails( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_CMT_TEXT 10064
#define IDC_FC_CLEAR 10065
#define IDC_RATELIST 10066
#define IDCOK 10067
#define IDCCANCEL 10068
wxSizer *commentDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_LST 10069
#define IDC_CMSTATUS 10070
#define IDCREF 10071
wxSizer *commentLstDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_ANIMATE 10072
#define ID_HTTPDOWNLOADPROGRESS 10073
#define IDC_DOWNLOADSIZE 10074
#define ID_HTTPCANCEL 5101
wxSizer *downloadDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_IPADDRESS 10075
#define ID_IPORT 10076
#define ID_USERNAME 10077
#define ID_USERHASH 10078
#define ID_ADDFRIEND 10079
#define ID_CLOSEDLG 10080
wxSizer *addFriendDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_BTNRELSHARED 10081
#define ID_SHFILELIST 10082
#define IDC_SREQUESTED 10083
#define IDC_SREQUESTED2 10084
#define IDC_SACCEPTED 10085
#define IDC_SACCEPTED2 10086
#define IDC_STRANSFERRED 10087
#define IDC_STRANSFERRED2 10088
wxSizer *sharedfilesDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_DLOADSCOPE 10089
#define IDC_C0 10090
#define IDC_C0_3 10091
#define IDC_C0_2 10092
#define ID_ULOADSCOPE 10093
#define IDC_C1 10094
#define IDC_C1_3 10095
#define IDC_C1_2 10096
#define ID_OTHERS 10097
#define IDC_S3 10098
#define IDC_S0 10099
#define ID_ACTIVEC 10100
#define IDC_S1 10101
wxSizer *statsDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_DNAME 10102
#define ID_DHASH 10103
#define ID_DSOFT 10104
#define ID_DVERSION 10105
#define ID_DIP 10106
#define ID_DID 10107
#define ID_DSIP 10108
#define ID_DSNAME 10109
#define IDT_OBFUSCATION 10110
#define IDT_KAD 10111
#define ID_DDOWNLOADING 10112
#define ID_DAVDR 10113
#define ID_DAVUR 10114
#define ID_DDOWN 10115
#define ID_DDUP 10116
#define ID_DDOWNTOTAL 10117
#define ID_DUPTOTAL 10118
#define ID_DRATIO 10119
#define IDC_CDIDENT 10120
#define ID_DRATING 10121
#define ID_DSCORE 10122
#define ID_CLOSEWND 10123
wxSizer *clientDetails( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_NICK 10124
#define IDC_LANGUAGE 10125
#define IDC_NEWVERSION 10126
#define IDC_STARTMIN 10127
#define IDC_EXIT 10128
#define IDC_ENABLETRAYICON 10129
#define IDC_MINTRAY 10130
#define IDC_TOOLTIPDELAY 10131
#define IDC_BROWSER 10132
#define IDC_BROWSERSELF 10133
#define IDC_SELBROWSER 10134
#define IDC_BROWSERTABS 10135
#define IDC_VIDEOPLAYER 10136
#define IDC_BROWSEV 10137
#define IDC_VIDEOBACKUP 10138
wxSizer *PreferencesGeneralTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_MAXDOWN 10139
#define IDC_MAXUP 10140
#define IDC_SLOTALLOC 10141
#define IDC_PORT 10142
#define IDC_UDPPORT 10143
#define IDC_UDPDISABLE 10144
#define IDC_ADDRESS 10145
#define ID_TEXT_CLIENT_UDP_PORT 10146
#define IDC_MAXSOURCEPERFILE 10147
#define IDC_MAXCON 10148
#define IDC_NETWORKED2K 10149
#define IDC_NETWORKKAD 10150
#define IDC_UPNP_ENABLED 10151
#define IDC_UPNPTCPPORT 10152
#define IDC_AUTOCONNECT 10153
#define IDC_RECONN 10154
#define IDC_SHOWOVERHEAD 10155
wxSizer *PreferencesConnectionTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_REMOVEDEAD 10156
#define IDC_SERVERRETRIES 10157
#define IDC_AUTOSERVER 10158
#define IDC_EDITADR 10159
#define IDC_UPDATESERVERCONNECT 10160
#define IDC_UPDATESERVERCLIENT 10161
#define IDC_SCORE 10162
#define IDC_SMARTIDCHECK 10163
#define IDC_SAFESERVERCONNECT 10164
#define IDC_AUTOCONNECTSTATICONLY 10165
#define IDC_MANUALSERVERHIGHPRIO 10166
wxSizer *PreferencesServerTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_ICH 10167
#define IDC_AICHTRUST 10168
#define IDC_ADDNEWFILESPAUSED 10169
#define IDC_DAP 10170
#define IDC_PREVIEWPRIO 10171
#define IDC_UAP 10172
#define IDC_FULLCHUNKTRANS 10173
#define IDC_STARTNEXTFILE 10174
#define IDC_STARTNEXTFILE_SAME 10175
#define IDC_SRCSEEDS 10176
#define IDC_CHECKDISKSPACE 10177
#define IDC_MINDISKSPACE 10178
#define IDC_ALLOCFULLFILE 10179
wxSizer *PreferencesFilesTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_INCFILES 10180
#define IDC_SELINCDIR 10181
#define IDC_TEMPFILES 10182
#define IDC_SELTEMPDIR 10183
#define IDC_SHARESELECTOR 10184
#define IDC_SHAREHIDDENFILES 10185
wxSizer *PreferencesDirectoriesTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_SLIDERINFO 10186
#define IDC_SLIDER 10187
#define IDC_SLIDERINFO3 10188
#define IDC_SLIDER3 10189
#define IDC_SLIDERINFO4 10190
#define IDC_SLIDER4 10191
#define IDC_COLORSELECTOR 10192
#define IDC_COLOR_BUTTON 10193
#define IDC_SLIDERINFO2 10194
#define IDC_SLIDER2 10195
#define IDC_CLIENTVERSIONS 10196
#define IDC_DOWNLOAD_CAP 10197
#define IDC_UPLOAD_CAP 10198
wxSizer *PreferencesStatisticsTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_MAXCON5SEC 10199
#define IDC_FILEBUFFERSIZE_STATIC 10200
#define IDC_FILEBUFFERSIZE 10201
#define IDC_QUEUESIZE_STATIC 10202
#define IDC_QUEUESIZE 10203
#define IDC_SERVERKEEPALIVE_LABEL 10204
#define IDC_SERVERKEEPALIVE 10205
wxSizer *PreferencesaMuleTweaksTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_PERCENT 10206
#define IDC_PROGBAR 10207
#define IDC_3DDEPTH 10208
#define IDC_USESKINFILES 10209
#define IDC_SKIN 10210
#define IDC_AUTOSORT 10211
#define IDC_FED2KLH 10212
#define IDC_EXTCATINFO 10213
#define IDC_SHOWRATEONTITLE 10214
#define IDC_VERTTOOLBAR 10215
#define IDC_SHOWPARTFILENUMBER 10216
wxSizer *PreferencesGuiTweaksTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_ENABLE_WEB 10217
#define IDC_WEB_PORT 10218
#define IDC_UPNP_WEBSERVER_ENABLED 10219
#define IDC_WEBUPNPTCPPORT 10220
#define IDC_WEB_REFRESH_TIMEOUT 10221
#define IDC_WEB_GZIP 10222
#define IDC_ENABLE_WEB_LOW 10223
#define IDC_WEB_PASSWD 10224
#define IDC_WEB_PASSWD_LOW 10225
#define IDC_WEBTEMPLATE 10226
#define IDC_EXT_CONN_ACCEPT 10227
#define IDC_EXT_CONN_PASSWD 10228
#define IDC_EXT_CONN_IP 10229
#define IDC_EXT_CONN_TCP_PORT 10230
#define IDC_UPNP_EC_ENABLED 10231
wxSizer *PreferencesRemoteControlsTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

extern wxSizer *prefs_sizer;
#define ID_PREFSLISTCTRL 10232
#define ID_PREFS_OK_TOP 10233
#define ID_PREFS_CANCEL_TOP 10234
wxSizer *preferencesDlgTop( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_TITLE 10235
#define IDC_COMMENT 10236
#define IDC_INCOMING 10237
#define IDC_BROWSE 10238
#define IDC_PRIOCOMBO 10239
#define ID_BOX_CATCOLOR 10240
#define IDC_CATCOLOR 10241
wxSizer *CategoriesEditWindow( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_SPLATTER 10242
wxSizer *transferDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_SERVERINFO 10243
#define ID_BTN_RESET_SERVER 10244
wxSizer *ServerInfoLog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_LOGVIEW 10245
#define ID_BTN_RESET 10246
wxSizer *aMuleLog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_UPDATELIST 10247
#define IDC_SERVERLISTURL 10248
#define IDC_SERVERNAME 10249
#define IDC_IPADDRESS 10250
#define IDC_SPORT 10251
#define ID_ADDTOLIST 10252
#define IDC_ED2KDISCONNECT 10253
#define ID_SERVERLIST 10254
wxSizer *serverListDlgUp( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_SRVLOG_NOTEBOOK 10255
wxSizer *serverListDlgDown( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_UPDATEKADLIST 10256
#define IDC_NODESLISTURL 10257
#define ID_KADSCOPE 10258
#define ID_NODE_IP1 10259
#define ID_NODE_IP2 10260
#define ID_NODE_IP3 10261
#define ID_NODE_IP4 10262
#define ID_NODE_PORT 10263
#define ID_NODECONNECT 10264
#define ID_KNOWNNODECONNECT 10265
#define ID_KADDISCONNECT 10266
wxSizer *KadDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_ED2KINFO 10267
wxSizer *ED2K_Info( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_SUPPORT_PO 10268
#define IDC_ENABLE_PO_OUTGOING 10269
#define IDC_ENFORCE_PO_INCOMING 10270
#define IDC_SEESHARES 10271
#define IDC_IPFCLIENTS 10272
#define IDC_IPFSERVERS 10273
#define IDC_IPFRELOAD 10274
#define IDC_IPFILTERURL 10275
#define IDC_IPFILTERUPDATE 10276
#define IDC_AUTOIPFILTER 10277
#define ID_IPFILTERLEVEL 10278
#define IDC_FILTERLAN 10279
#define IDC_PARANOID 10280
#define IDC_IPFILTERSYS 10281
#define IDC_SECIDENT 10282
wxSizer *PreferencesSecurityTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_ONLINESIG 10283
#define IDC_OSUPDATE 10284
#define IDC_OSDIR 10285
#define IDC_SELOSDIR 10286
wxSizer *PreferencesOnlineSigTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_MSGFILTER 10287
#define IDC_MSGFILTER_ALL 10288
#define IDC_MSGFILTER_NONFRIENDS 10289
#define IDC_MSGFILTER_NONSECURE 10290
#define IDC_MSGFILTER_WORD 10291
#define IDC_MSGWORD 10292
#define IDC_FILTERCOMMENTS 10293
#define IDC_COMMENTWORD 10294
wxSizer *PreferencesMessagesTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_PROXY_ENABLE_PROXY 10295
#define ID_PROXY_TYPE 10296
#define ID_PROXY_NAME 10297
#define ID_PROXY_PORT 10298
#define ID_PROXY_ENABLE_PASSWORD 10299
#define ID_PROXY_USER 10300
#define ID_PROXY_PASSWORD 10301
#define ID_PROXY_AUTO_SERVER_CONNECT_WITHOUT_PROXY 10302
wxSizer *PreferencesProxyTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_REMOTE_HOST 10303
#define ID_REMOTE_PORT 10304
#define ID_EC_LOGIN 10305
#define ID_EC_PASSWD 10306
#define ID_EC_SAVE 10307
wxSizer *CoreConnect( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_VERBOSEDEBUG 10308
#define ID_DEBUGCATS 10309
wxSizer *PreferencesDebug( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

extern wxSizer *IDC_CURJOB;
#define IDC_CONV_PB_LABEL 10310
#define IDC_CONV_PROZENT 10311
#define IDC_CONV_PB_CURRENT 10312
#define IDC_JOBLIST 10313
#define IDC_ADDITEM 10314
#define IDC_RETRY 10315
#define IDC_CONVREMOVE 10316
wxSizer *convertDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_KADINFO 10317
wxSizer *Kad_Info( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

extern wxSizer *m_networknotebooksizer;
#define ID_NETNOTEBOOK 10318
wxSizer *NetDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

extern wxSizer *IDC_PREFS_EVENTS_PAGE;
#define IDC_EVENTLIST 10319
wxSizer *PreferencesEventsTab( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

#define ID_BUTTONCONNECT 10320
#define ID_BUTTONNETWORKS 10321
#define ID_BUTTONSEARCH 10322
#define ID_BUTTONTRANSFER 10323
#define ID_BUTTONSHARED 10324
#define ID_BUTTONMESSAGES 10325
#define ID_BUTTONSTATISTICS 10326
#define ID_BUTTONNEWPREFERENCES 10327
#define ID_BUTTONIMPORT 10328
#define ID_ABOUT 10329
void muleToolbar( wxToolBar *parent );

// Declare bitmap functions

wxBitmap clientImages( size_t index );

wxBitmap dlStatusImages( size_t index );

wxBitmap connImages( size_t index );

wxBitmap moreImages( size_t index );

wxBitmap amuleSpecial( size_t index );

wxBitmap connButImg( size_t index );

wxBitmap amuleDlgImages( size_t index );

#endif

// End of generated file
