<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

// if you are translating this file, please replace all special characters with
// html unicode entities (&#nnn;). It's not always necessary, but ensures that
// there are minimal problems displaying the text in all browsers.

$text["dayabbr"]	= "d";
$text["hourabbr"]	= "h";
$text["minabbr"]	= "m";
$text["secabbr"]	= "s";
$text["runtimemsg"]	= "has been running for";
$text["norunmsg"]	= "is not running";
$text["connmsg"]	= "is connecting";
$text["highidmsg"]	= "is online with HighID";
$text["lowidmsg"]	= "is online with LowID";
$text["offrunmsg"]	= "is offline";
$text["amulerun"]	= "(aMule running)";
$text["amulenorun"]	= "(aMule not running)";
$text["sharedfiles"]	= "Shared files";

// Kad
$text["kadonmsg"]       = "( Kad: on )";
$text["kadfwmsg"]       = "( Kad: firewalled)";
$text["kadoffmsg"]      = "( Kad: off )";
$text["kadstatus"]      = "Kad Status";
$text["kadfw"]     	= "Firewalled";
$text["kadon"]         	= "Connected";
$text["kadoff"]        	= "Disconnected";
// try to keep these next three short, otherwise the signature
// image will look messy
$text["na"]		= "N/A";
$text["rx"]		= "RX";
$text["tx"]		= "TX";

$text["queuedclients"]	= "Queued clients";
$text["transrate"]	= "KiB/s";
$text["gigabytes"]	= "GiB";
$text["client"]		= "Client";
$text["ed2kstatus"]	= "eD2K Status";
$text["nick"]		= "Nick";
$text["localtime"]	= "Local time";
$text["rxspeed"]	= "RX speed";
$text["txspeed"]	= "TX speed";
$text["rxtotal"]	= "RX total";
$text["txtotal"]	= "TX total";
$text["osversion"]	= "OS version";
$text["hostuptime"]	= "Host uptime";
$text["servername"]	= "Server name";
$text["serveraddr"]	= "Server address:port";
$text["ed2klink"]	= "ED2K link";
$text["general"]	= "General";
$text["server"]		= "Server";
$text["signature"]	= "Signature";
$text["connecting"]	= "Connecting";
$text["online"]		= "Online";
$text["offline"]	= "Offline";
$text["language"]	= "Language";
$text["submit"]		= "Submit";

$text["sigfileerr"]	= "Couldn't open signature file";
$text["baseimgerr"]	= "Cannot find base image";
$text["iconerr"]	= "Cannot find one or more icons";

?>
