.TH ED2K "1" "Mars 2005" "Prise en charge des liens ED2k d'aMule v1.1.0" "Outil pour aMule"
.SH NOM
ed2k \- prise en charge des liens ED2K d'aMule
.SH SYNOPSYS
.B ed2k
.I <lien_ED2k>
.PP
.B ed2k
.RB [ \-\-help ]
.RB [ \-\-version ]
.SH DESCRIPTION
Envoi le lien ED2K \fI<lien_ED2k>\fR à aMule, i.e. écrit celui\-ci dans ~/.aMule/ED2KLinks, qui est examiné par aMule chaque seconde en quête de nouveaux liens.
\fBed2k\fR accepte en lien un fichier, un serveur et une liste de serveurs.
.SS "Usage:"
.TP
\fB\-\-help\fR
Afficher l'aide d'utilisation.
.TP
\fB\-\-version\fR
Afficher les informations sur la version courante.
.SH FICHIERS
~/.aMule/ED2KLinks
.SH SIGNALEMENT DES BUGS
Reportez les bugs sur notre forum (\fIhttp://forum.amule.org/\fR), ou dans notre bugtracker (\fIhttp://bugs.amule.org/\fR).
N'utilisez ni un e-mail, ni notre liste de diffusion ni ne reportez directement un bug à un membre de notre equipe.
.SH COPYRIGHT
aMule et tous les utilitaires associés sont distribués sous licence GNU General Public License.
.SH VOIR AUSSI
\fBamule\fR(1)
.SH TRADUCTION
ThePolish, 2005
