.TH ED2K "1" "2005 március" "aMule ED2k link parser v1.1.0" "aMule segédprogramok"
.SH NÉV
ed2k \- aMule ED2k hivatkozás feldolgozó
.SH ÁTTEKINTÉS
.B ed2k
.I <ED2k_hivatkozás>
.PP
.B ed2k
.RB [ \-\-help ]
.RB [ \-\-version ]
.SH LEÍRÁS
aMule ED2k hivatkozás feldolgozó v1.1.0.
Elküldi a megadott \fI<ED2k_hivatkozás>\fR-t az aMule-nak, azaz a \fI~/.aMule/ED2KLinks\fR fájlba írja, amelyet az aMule minden másodpercben ellenõriz.
Az \fBed2k\fR program elfogad fájl, szerver és szerver-lista hivatkozásokat.
.SS "Használat:"
.TP
\fB\-\-help\fR
Kiírja ezt a súgót.
.TP
\fB\-\-version\fR
Kiírja a verzió információt.
.SH FÁJLOK
~/.aMule/ED2KLinks
.SH HIBÁK JELENTÉSE
A hibákat kérjük vagy a fórumon (\fIhttp://forum.amule.org/\fR), vagy a hibakövetõben (\fIhttp://bugs.amule.org/\fR) jelentsék.
Hibákról kérjük ne írjanak levelet (e-mail-t) se a levelzési listára, se közvetlenül valamelyik fejlesztõnek.
.SH COPYRIGHT
Az aMule és az összes hozzá tartozó segédprogram a GNU General Public Licence védelme alatt áll.
.SH LÁSD MÉG
\fBamule\fR(1)
.SH MAGYAR FORDÍTÁS
Dévai Tamás <gonosztopi@amule.org>
