.TH ALC 1 "January 2007" "aLinkCreator" "aMule utilities"
.SH NAME
aLinkCreator \- the aMule ED2k link creator
.SH SYNOPSIS
.B alc
.SH DESCRIPTION
\fBalc\fR is a graphical utility to create an ED2k link to any file on your computer.

This programm doesn't take any arguments.
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
\fBalcc\fR(1), \fBamule\fR(1)
