.TH ALC 1 "January 2010" "aLinkCreator" "aMule utilities"
.als B_untranslated B
.SH NAME
aLinkCreator \- the aMule eD2k link creator
.SH SYNOPSIS
.B_untranslated alc
.SH DESCRIPTION
\fBalc\fR is a graphical utility to create an eD2k link to any file on your computer.

This app doesn't take any arguments.
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
.B_untranslated alcc\fR(1), \fBamule\fR(1)
.SH AUTHOR
This manpage was written by Vollstrecker <amule@vollstreckernet.de>
