.TH ALCC "1" "March 2005" "aMule ED2k links calculator" "aMule utilities"
.SH NAME
alcc \- text based ED2K links calculator for aMule
.SH SYNOPSIS
.B alcc
.RB [ \-p ]
.RB [ \-v ]
.I <inputfiles_list>
.PP
.B alcc
.RB [ \-h ]
.SH DESCRIPTION
Compute the ED2K links of all the input files given in the \fI<inputfiles_list>\fR (There can be one or more files).
.SS "Usage:"
.TP
\fB\-h, \-\-help\fR
Prints this help.
.TP
\fB\-v, \-\-verbose\fR
Be verbose: print calculation steps.
.TP
\fB\-p, \-\-parthashes\fR
Compute and add part hashes to the computed ED2K links.
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
\fBalc\fR(1), \fBamuled\fR(1), \fBamulecmd\fR(1), \fBamuleweb\fR(1), \fBcas\fR(1), \fBed2k\fR(1), \fBwxcas\fR(1), \fBxas\fR(1)
