.TH XAS 1 "Marzo 2005" "xas" "Utilidades de aMule"
.SH NOMBRE
xas \- Estadísticas de aMule para X\-Chat
.SH SINOPSIS
.B nada
.SH DESCRIPCIÓN
.B xas
es un plug-in para X\-Chat. Para cargarlo, lea la documentación de X\-Chat.
Para ejecutarlo, escriba /xas y mostrará sus estadísticas en el canal que este visualizando en ese momento.
Estas estadísticas se botiene de la firma de aMule.
.SH AUTOR
\fBxas\fR fué escrito originalmente por niet
.SH SEE ALSO
\fBamule\fR(1)
