.TH XAS 1
.SH NAME
xas \- X\-Chat aMule Statistics
.SH SYNTAX
.B keine
.SH "Beschreibung"
.B xas
ist ein Plugin für XChat. Wie man es lädt ist dessen Doku zu entnehmen. 
Nach dem Laden tippe einfach /xas, und es werden Statistiken über dein 
aMule an den Channel in dem du dich befindest gesendet. Diese werden 
aus deiner Online-Signatur-Datei gelesen.
Damit das funktioniert, muss in aMule die Option "Online Signatur" angeschaltet sein!
.SH PROBLEME BERICHTEN
Bitte berichte Fehler im Programm entweder im Forum (\fIhttp://forum.amule.org/\fR), oder in unserem Bugtracker (\fIhttp://bugs.amule.org/\fR).
Bitte berichte keine Fehler per E-Mail, auch nicht an unsere Mailingliste oder direkt an ein Teammitglied.
.SH COPYRIGHT
aMule und alle seine Tools stehen unter der GNU General Public License.
.SU SIEHE AUCH
\fBamule\fR(1)
