.TH AMULEGUI 1
.SH NAME
amulegui \- aMule Kontollprogramm mit Graphischer Oberfläche
.SH SYNOPSIS
.B amulegui
.SH "DESCRIPTION"
.B amulegui
ist ein Kontrollprogramm das, per EC, mit amule oder amuled verbunden werden kann. Man
kann damit das verbundene Programm bedienen. amulegui bietet fast die gesamte Funktionalität
die amule bietet, auch wenn das Kernprogramm auf einem anderten Rechner läuft.
.SH PROBLEME BERICHTEN
Bitte berichte Fehler im Programm entweder im Forum (\fIhttp://forum.amule.org/\fR), oder in unserem Bugtracker (\fIhttp://bugs.amule.org/\fR).
Bitte berichte keine Fehler per E-Mail, auch nicht an unsere Mailingliste oder direkt an ein Teammitglied.
.SH COPYRIGHT
aMule und alle seine Tools stehen unter der GNU General Public License.
.SH SIEHE AUCH
\fBalc\fR(1), \fBalcc\fR(1), \fBamuled\fR(1), \fBamulecmd\fR(1), \fBamuleweb\fR(1), \fBcas\fR(1), \fBed2k\fR(1), \fBwxcas\fR(1), \fBxas\fR(1)
