.TH AMULE 1 "March 2005" "aMule v2.0.0" "aMule"
.SH NAME
amule \- the all\-platform eMule p2p client
.SH SYNOPSIS
.B amule
.RB [ \-v ]
.RB [ \-h ]
.RB [ \-i ]
.RB [ \-geometry " " \fI<geom> ]
.RB [ \-d ]
.RB [ \-o ]
.SH BESCHREIBUNG
.TP
\fB\-v\fR, \fB\-\-version\fR
Zeigt die Versionsnummer an.
.TP
\fB\-h\fR, \fB\-\-help\fR
Zeigt diese Infos an.
.TP
\fB-i\fR, \fB\-\-enable\-stdin\fR
Schaltet stdin nicht ab.
.TP
\fB\-geometry\fR \fI<geom>\fR
Setzt die Breite und Höhe der Anwendung.
\fI<geom>\fR es wird das selbe standart Format wie bei andern X11 Anwendungen genutzt:	[\fB=\fR][\fI<width>\fR{\fBxX\fR}\fI<height>\fR][{\fB+-\fR}\fI<xoffset>\fR{\fB+-\fR}\fI<yoffset>\fR]
.TP
\fB\-d\fR, \fB\-\-disable\-fatal\fR
Verarbeitet keine fatalen Fehler.
.TP
\fB-o\fR, \fB\-\-log\-stdout\fR
Gibt log messages nach stdout.
.SH Dateien
~/.aMule/*
.SH PROBLEME BERICHTEN
Bitte berichte Fehler im Programm entweder im Forum (\fIhttp://forum.amule.org/\fR), oder in unserem Bugtracker (\fIhttp://bugs.amule.org/\fR).
Bitte berichte keine Fehler per E-Mail, auch nicht an unsere Mailingliste oder direkt an ein Teammitglied.
.SH COPYRIGHT
aMule und alle seine Tools stehen unter der GNU General Public License.
.SH SIEHE AUCH
\fBalc\fR(1), \fBalcc\fR(1), \fBamuled\fR(1), \fBamulecmd\fR(1), \fBamulecmdDLG\fR(1), \fBamuleweb\fR(1), \fBamulewebDLG\fR(1), \fBcas\fR(1), \fBed2k\fR(1), \fBwxcas\fR(1), \fBxas\fR(1)
