.TH AMULED 1 "2005" "aMule Deabrua 2.0.0b" "aMule Lanabesa"
.SH NAME
amuled \- Plataforma orotarako eMule p2p bezeroa \- deabru bertsioa
.SH LABURPENA
.B amuled
.RB [ \-v ]
.RB [ \-h ]
.RB [ \-i ]
.RB [ \-f ]
.RB [ \-c " " \fI<dir> ]
.RB [ \-d ]
.RB [ \-o ]
.RB [ \-r ]

.SH AZALPENA
.TP
\fB\-v\fR, \fB\-\-version\fR
Bertsio zenbakia bistaratzen du.
.TP
\fB\-h\fR, \fB\-\-help\fR
Azlapen hau bistaratzen du.
.TP
\fB-i\fR, \fB\-\-enable\-stdin\fR
Ez sarrera estandarra ezgaitu.
.TP
\fB\-f\fR, \fB\-\-full\-daemon\fR
Atzeko planoan ireki
.TP
\fB\-c\fR, \fB\-\-config\-dir\fR=\fI<dir>\fR
Konfigurazioa home-etik beharrean <dir>-etik irakurri.
.TP
\fB\-d\fR, \fB\-\-disable\-fatal\fR
Ez kudeatu salbuespen konponezinak.
.TP
\fB-o\fR, \fB\-\-log\-stdout\fR
Erregistro mezuak irteera estandarrean inprimatu
.SH FITXATEGIAK
~/.aMule/*
.SH ZORRIEN BERRI EMATEN
Mesedez zorrien berri emateko gure foroa (\fIhttp://forum.amule.org/\fR), edo gure zorri kudeatzailea
(\fIhttp://bugs.amule.org/\fR) erabili.
Mesedez ez eman zorrien berri epostaz, ez gure eposta zerrendan ez taldeko partaideei.
.SH COPYRIGHT
aMule eta inguruneko lanabes guztiak GNU Lizentzia Publiko Orokorraz banatzen dira.
.SH IKUSI ERE
\fBalcc\fR(1), \fBamule\fR(1), \fBamulecmd\fR(1), \fBamulegui\fR(1), \fBamuleweb\fR(1), \fBcas\fR(1), \fBed2k\fR(1)
