.TH AMULECMD 1 "March 2005" "aMuleCmd v2.0.0" "aMule utilities"
.SH NAME
amulecmd \- Text-based program to control aMule
.SH SYNOPSIS
.B amulecmd
.RB [ \-h " " \fI<host> ]
.RB [ \-p " " \fI<port> ]
.RB [ \-P " " \fI<passwd> ]
.RB [ \-f " " \fI<path> ]
.RB [ \-q ]
.RB [ \-v ]
.RB [ \-w ]
.RB [ \-c " " \fI<command> ]
.PP
.B amulecmd
.RB [ \-\-help ]
.RB [ \-\-version ]
.SH DESCRIPTION
\fBamulecmd\fR is a text-based client to control aMule.
Useful help can be obtained when you launch the program.
.PP
\fBamulecmdDLG\fR is the GUI version of \fBamulecmd\fR, and the only difference is that it does not accept the \fB\-c\fR option.
.TP
\fB\-h\fR, \fB\-\-host\fR=\fI<host>\fR
host where aMule is running (default: \fIlocalhost\fR). \fI<host>\fR might be an IP address or a DNS name
.TP
\fB\-p\fR, \fB\-\-port\fR=\fI<port>\fR
aMule's port for External Connections, as set in Preferences->Remote Controls (default: \fI4712\fR)
.TP
\fB\-P\fR, \fB\-\-password\fR=\fI<passwd>\fR
External Connections password
.TP
\fB\-f\fR, \fB\-\-config\-file\fR=\fI<path>\fR
use the given configuration file. Default configuration file is \fI~/.aMule/remote.conf\fR
.TP
\fB\-q\fR, \fB\-\-quiet\fR
do not print any output to stdout. This seems to be a very much useless option with \fBamulecmd\fR.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
be verbose \- show also debug messages
.TP
\fB\-w\fR, \fB\-\-write\-config\fR
write command line options to config file and exit
.TP
\fB\-c\fR, \fB\-\-command\fR=\fI<command>\fR
execute \fI<command>\fR as if it was entered at amulecmd's prompt and exit (unavailable in GUI version)
.TP
\fB\-\-help\fR
display usage help information and exit
.TP
\fB\-\-version\fR
output program version information and exit
.SH FILES
~/.aMule/remote.conf
.SH EXAMPLE
Typically amulecmd will be first run as:
.PP
\fBamulecmd\fR \fB\-h\fR \fIhostname\fR \fB\-p\fR \fIECport\fR \fB\-P\fR \fIECpassword\fR \fB\-w\fR
.PP
This will save these settings to \fI$HOME/.aMule/remote.conf\fR, and later you only need to type:
.PP
.B amulecmd
.PP
Of course, you don't have to follow this example.
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
\fBamule\fR(1), \fBamuleweb\fR(1)
