.TH AMULEWEBDLG 1
.SH NAME
amulewebDLG \- aMule web server \- GUI version
.SH SYNOPSIS
.B amulewebDLG
.RB [ \-h " " \fI<host> ]
.RB [ \-p " " \fI<port> ]
.RB [ \-P " " \fI<passwd> ]
.RB [ \-f " " \fI<path> ]
.RB [ \-q ]
.RB [ \-v ]
.RB [ \-w ]
.RB [ \-t " " \fI<name> ]
.RB [ \-s " " \fI<port> ]
.RB [ \-z ]
.RB [ \-Z ]
.RB [ \-A " " \fI<adminpass> ]
.RB [ \-G " " \fI<guestpass> ]
.RB [ \-a ]
.RB [ \-d ]
.RB [ \-L ]
.PP
.B amulewebDLG
.RB [ \-\-help ]
.RB [ \-\-version ]
.PP
.B amulewebDLG
.RB [ \-\-amule\-config\-file=\fI<path> ]
.SH DESCRIPTION
amuleweb manages your access to amule through a webbrowser.
.PP
amulewebDLG is completely the same as \fBamuleweb\fR(1), except that it has a nice(?) GUI interface.
For a description of command-line parameters and for more information see \fBamuleweb\fR(1).
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
\fBamule\fR(1), \fBamulecmd\fR(1), \fBamuleweb\fR(1)
