.TH AMULECMDDLG 1
.SH NAME
amulecmd \- Text-basiertes Client Programm um aMule zu steuern, mit GUI
.SH SYNOPSIS
.B amulecmdDLG
.RB [ \-h " " \fI<host> ]
.RB [ \-p " " \fI<port> ]
.RB [ \-P " " \fI<passwd> ]
.RB [ \-f " " \fI<path> ]
.RB [ \-q ]
.RB [ \-v ]
.RB [ \-w ]
.PP
.B amulecmdDLG
.RB [ \-\-help ]
.RB [ \-\-version ]
.SH DESCRIPTION
amulecmd ist ein Text-basiertes Programm um aMule zu steuern.
Nuetzliche Hilfe wird angezeigt wenn das Programm gestartet wird.
.PP
amulecmdDLG ist genau dasselbe wie \fBamulecmd\fR(1), ausser das es eine nette(?) GUI Oberfaeche hat.
Fuer eine detaiert Beschreibung der Kommandozeilen Optionen und mehr Informationen siehe \fBamulecmd\fR(1).
.SH ACHTUNG
Der GUI Client akzerptiert die \fB\-c\fR Kommandooption nicht.
.SH PROBLEME BERICHTEN
Bitte berichte Fehler im Programm entweder im Forum (\fIhttp://forum.amule.org/\fR), oder in unserem Bugtracker (\fIhttp://bugs.amule.org/\fR).
Bitte berichte keine Fehler per E-Mail, zu unserer Mailingliste oder direkt zu einem Teammitglied.
.SH COPYRIGHT
aMule und alle seine Tools stehen unter der GNU General Public License.
.SH SIEHE AUCH
\fBamule\fR(1), \fBamulecmd\fR(1), \fBamuleweb\fR(1)
