.TH AMULED 1 "Mars 2005" "aMule Daemon v2.0.0" "aMule Daemon"
.SH NOM
amuled, le client p2p eMule \-multi\- platforme \- version daemon
.SH SYNOPSIS
.B amuled
.RB [ \-v ]
.RB [ \-h ]
.RB [ \-i ]
.RB [ \-d ]
.RB [ \-o ]
.SH DESCRIPTION
.TP
\fB\-v\fR, \fB\-\-version\fR
Afficher les informations sur la version courante.
.TP
\fB\-h\fR, \fB\-\-help\fR
Afficher l'aide d'utilisation.
.TP
\fB-i\fR, \fB\-\-enable\-stdin\fR
Ne pas désactiver stdin.
.TP
\fB\-d\fR, \fB\-\-disable\-fatal\fR
Ne pas prendre en charge une exception fatale.
.TP
\fB-o\fR, \fB\-\-log\-stdout\fR
Afficher les messages de log sur stdout.
.SH FICHIERS
~/.aMule/*
.SH SIGNALEMENT DES BUGS
Reportez les bugs sur notre forum (\fIhttp://forum.amule.org/\fR), ou dans notre bugtracker (\fIhttp://bugs.amule.org/\fR).
N'utilisez ni un e-mail, ni notre liste de diffusion ni ne reportez directement un bug à un membre de notre equipe.
.SH COPYRIGHT
aMule et tous les utilitaires associés sont distribués sous licence GNU General Public License.
.SH VOIR AUSSI
\fBalcc\fR(1), \fBamule\fR(1), \fBamulecmd\fR(1), \fBamuleweb\fR(1), \fBcas\fR(1), \fBed2k\fR(1)
.SH TRADUCTION
ThePolish, 2005
