.TH AMULEGUI 1 "January 2007" "aMuleGUI v2.2.0" "aMuleGUI"
.SH NAME
amulegui \- aMule control program with GUI
.SH SYNOPSIS
.B amulegui
.SH "DESCRIPTION"
.B amulegui
is a client program, and can be connected on amule or amuled via EC. You
can manage your amule program with it. It provides the almost same functionality
as amule, even if the core works on another computer.

This program doesn't take any arguments.
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
\fBalc\fR(1), \fBalcc\fR(1), \fBamuled\fR(1), \fBamulecmd\fR(1), \fBamuleweb\fR(1), \fBcas\fR(1), \fBed2k\fR(1), \fBwxcas\fR(1), \fBxas\fR(1)
.SH AUTHOR
This manpage was written by Julien Delange for Debian <julien AT gunnm DOT org>
This manpage was rewritten by Vollstrecker for aMule <amule@vollstreckernet.de>



