.TH ED2K "1" "March 2005" "aMule ED2k link parser v1.1.0" "Nutzer Kommandos"
.SH NAME
ed2k \- aMule ED2k link parser
.SH SYNOPSYS
.B ed2k
.I <ED2k_link>
.PP
.B ed2k
.RB [ \-\-help ]
.RB [ \-\-version ]
.SH BESCHREIBUNG
aMule ED2k link parser v1.1.0.
Sendet den gegebenen \fI<ED2k_link>\fR zu aMule, z.B schreibt es in die Datei ~/.aMule/ED2KLinks, welche von aMule jede Sekunde gechecked wird nach Links.
\fBed2k\fR akzeptiert Datein, Server und Serverlist Links.
.SS "BENUTZUNG:"
.TP
\fB\-\-help\fR
Gibt diese Hilfe aus.
.TP
\fB\-\-version\fR
Zeigt die Versionsnummer an.
.SH DATEIEN
~/.aMule/ED2KLinks
.SH PROBLEME BERICHTEN
Bitte berichte Fehler im Programm entweder im Forum (\fIhttp://forum.amule.org/\fR), oder in unserem Bugtracker (\fIhttp://bugs.amule.org/\fR).
Bitte berichte keine Fehler per E-Mail, auch nicht an unsere Mailingliste oder direkt an ein Teammitglied.
.SH COPYRIGHT
aMule und alle seine Tools stehen unter der GNU General Public License.
.SH SIEHE AUCH
\fBamule\fR(1)
