.TH ED2K "1" "March 2005" "aMule ED2k link parser v1.1.0" "aMule utilities"
.SH NAME
ed2k \- aMule ED2k link parser
.SH SYNOPSYS
.B ed2k
.I <ED2k_link>
.PP
.B ed2k
.RB [ \-\-help ]
.RB [ \-\-version ]
.SH DESCRIPTION
aMule ED2k link parser v1.1.0.
Sends the given \fI<ED2k_link>\fR to aMule, i.e. writes it to the file ~/.aMule/ED2KLinks, which will be checked by aMule every second for links.
\fBed2k\fR accepts file, server and serverlist links.
.SS "Usage:"
.TP
\fB\-\-help\fR
Prints this help.
.TP
\fB\-\-version\fR
Displays version info.
.SH FILES
~/.aMule/ED2KLinks
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
\fBamule\fR(1)
