<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$text["dayabbr"]	= "j";
$text["hourabbr"]	= "h";
$text["minabbr"]	= "m";
$text["secabbr"]	= "s";
$text["runtimemsg"]	= "fonctionne depuis";
$text["norunmsg"]	= "est arr&#234;t&#233;";
$text["connmsg"]	= "se connecte";
$text["highidmsg"]	= "est connect&#233; (high id)";
$text["lowidmsg"]	= "est connect&#233; (low id)";
$text["offrunmsg"]	= "n'est pas connect&#233;";
$text["amulerun"]	= "(aMule fonctionne)";
$text["amulenorun"]	= "(aMule est arr&#234;t&#233;)";
$text["sharedfiles"]	= "Fichiers partag&#233;s";

// try to keep these next three short, otherwise the signature
// image will look messy
$text["na"]		= "N/A";
$text["rx"]		= "RX";
$text["tx"]		= "TX";

$text["queuedclients"]	= "Clients en attente";
$text["transrate"]	= "Ko/s";
$text["gigabytes"]	= "Go";
$text["client"]		= "Client";
$text["status"]		= "Statut";
$text["nick"]		= "Pseudo";
$text["localtime"]	= "Heure locale";
$text["rxspeed"]	= "Vitesse de r&#233;ception";
$text["txspeed"]	= "Vitesse de transmission";
$text["rxtotal"]	= "Total re&#231;u";
$text["txtotal"]	= "Total transmis";
$text["osversion"]	= "Version d'OS";
$text["hostuptime"]	= "Temps de fonctionnement";
$text["servername"]	= "Nom du serveur";
$text["serveraddr"]	= "Adresse:port du serveur";
$text["ed2klink"]	= "Lien ED2K";
$text["general"]	= "G&#233;n&#233;ral";
$text["server"]		= "Serveur";
$text["signature"]	= "Signature";
$text["connecting"]	= "Connexion en cours";
$text["online"]		= "Connect&#233;";
$text["offline"]	= "D&#233;connect&#233;";
$text["language"]	= "Langue";
$text["submit"]		= "Envoyer";

$text["sigfileerr"]	= "Impossible d'ouvrir le fichier de signature";
$text["baseimgerr"]	= "Impossible de trouver l'image de fond";
$text["iconerr"]	= "Impossible de trouver un ou plusieurs ic&#244;nes";

?>
