.TH ED2K "1" "Marzo 2005" "aMule ED2k link parser v1.1.0" "Utilidades de aMule"
.SH NOMBRE
ed2k \- digeridor de enlaces eD2k a aMule
.SH SINOPSYS
.B ed2k
.I <enlace_eD2k>
.PP
.B ed2k
.RB [ \-\-help ]
.RB [ \-\-version ]
.SH DESCRIPCIÓN
aMule ED2k link parser v1.1.0.
Envía el enlace \fI<enlace_eD2k>\fR a aMule, es decir, lo añade al archivo ~/.aMule/ED2KLinks, el cual será leido por aMule en busca de nuevas descargas.
\fBed2k\fR acepta enlaces referidos a archivos, servidores y listas de servidores.
.SS "Uso:"
.TP
\fB\-\-help\fR
Muestra esta ayuda.
.TP
\fB\-\-version\fR
Muestra la versión del programa.
.SH ARCHIVOS
~/.aMule/ED2KLinks
.SH BUGS
Si descubre bugs, por favor comuníquelos en (\fIhttp://forum.amule.org/\fR), o en nuestro bugtracker (\fIhttp://bugs.amule.org/\fR).
Por favor, no comunique bugs por e-mail, ni a nuestro maillist ni directamente a ningún miembro del equipo de aMule.
.SH COPYRIGHT
aMule, y todas las utilidades que con el vienen, se distribuyen bajo la licencia GPL.
.SH VER
\fBamule\fR(1)
