.TH WXCAS 1 "Marzo 2005" "wxCas" "Utilidades de aMule"
.SH NOMBRE
wxcas \- Estadísticas de aMule con interfáz gráfica
.SH SINOPSIS
.B wxcas
.SH DESCRIPCIÓN
.B wxcas
es un programa para leer el contenido de la firma de tu cliente aMule en una amigable ventana.
Basado en el programa \fBcas\fR(1) de Pedro de Oliveira.
.PP
La documentación completa de wxcas se puede descargar de \fIhttp://download.berlios.de/amule/wxcas_user_manual.pdf\fR.
.SH AUTOR
\fBwxcas\fR ha sido escrito por ThePolish <thepolish@vipmail.ru>
.SH BUGS
Si descubre bugs, por favor comuníquelos en (\fIhttp://forum.amule.org/\fR), o en nuestro bugtracker (\fIhttp://bugs.amule.org/\fR).
Por favor, no comunique bugs por e-mail, ni a nuestro maillist ni directamente a ningún miembro del equipo de aMule.
.SH COPYRIGHT
aMule, y todas las utilidades que con el vienen, se distribuyen bajo la licencia GPL.
.SH VER
\fBamule\fR(1), \fBcas\fR(1)
