INCLUDE (FindBISON)
INCLUDE (FindFLEX)

EXECUTE_PROCESS (COMMAND ${FLEX_EXECUTABLE} --help
	OUTPUT_VARIABLE FLEX_HELP
	)

	STRING (REGEX MATCH header-file FLEX_MATCH "${FLEX_HELP}")

IF (WIN32 AND DOWNLOAD_AND_BUILD_DEPS AND (NOT BISON_FOUND OR NOT FLEX_FOUND))
	EXTERNALPROJECT_ADD (BISON_FLEX
		GIT_REPOSITORY https://github.com/lexxmark/winflexbison
		GIT_TAG v2.5.22
		GIT_PROGRESS TRUE
		CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
 		BUILD_COMMAND ${CMAKE_COMMAND} --build . --config Release
 		INSTALL_COMMAND ${CMAKE_COMMAND} --install . --config Release
	)

	LIST (APPEND EXTERNAL_DEPS BISON_FLEX)
ENDIF (WIN32 AND DOWNLOAD_AND_BUILD_DEPS AND (NOT BISON_FOUND OR NOT FLEX_FOUND))
