INCLUDE (CheckIncludeFileCXX)

FIND_PACKAGE (Boost ${MIN_BOOST_VERSION} COMPONENTS system)

IF (Boost_FOUND)
	CHECK_INCLUDE_FILE_CXX (boost/asio.hpp ASIO_SOCKETS -lboost_system)

	IF (ASIO_SOCKETS)
		CHECK_INCLUDE_FILE_CXX (boost/system/error_code.hpp HAVE_BOOST_SYSTEM_ERROR_CODE_HPP -lboost_system)

		IF (NOT HAVE_BOOST_SYSTEM_ERROR_CODE_HPP)
			SET (ENABLE_BOOST FALSE)
		ENDIF (NOT HAVE_BOOST_SYSTEM_ERROR_CODE_HPP)
	ELSE (ASIO_SOCKETS)
		SET (ENABLE_BOOST FALSE)
	ENDIF (ASIO_SOCKETS)
ELSE (Boost_FOUND)
	SET (ENABLE_BOOST FALSE)
ENDIF (Boost_FOUND)
