INCLUDE (CheckIncludeFile)

IF (GEOIP_INCLUDE_DIR)
	SET (CMAKE_REQUIRED_INCLUDES "${GEOIP_INCLUDE_DIR}")
ENDIF (GEOIP_INCLUDE_DIR)

CHECK_INCLUDE_FILE (GeoIP.h GEOIP_H)

IF (GEOIP_INCLUDE_DIR)
	SET (CMAKE_REQUIRED_INCLUDES)
ENDIF (GEOIP_INCLUDE_DIR)

IF (GEOIP_H)
	FIND_LIBRARY (LIBGEOIP GeoIP)

	IF (NOT LIBGEOIP AND GEOIP_INCLUDE_DIR)
		FIND_LIBRARY (LIBGEOIP GeoIP
			PATHS ${GEOIP_INCLUDE_DIR}
		)
	ENDIF (NOT LIBGEOIP AND GEOIP_INCLUDE_DIR)

	IF (NOT LIBGEOIP)
		SET (ENABLE_IP2COUNTRY FALSE)
		MESSAGE (STATUS "GeoIP lib not found, disabling support")
	ELSE (NOT LIBGEOIP)
		MESSAGE (STATUS "GeoIP found useable")
	ENDIF (NOT LIBGEOIP)
ELSE (GEOIP_H)
	SET (ENABLE_IP2COUNTRY FALSE)
	MESSAGE (STATUS "GeoIP headers not found, disabling support")
ENDIF (GEOIP_H)
