IF (NOT GEOIP_LIBRARY)
	INCLUDE (CheckIncludeFile)

	IF (GEOIP_INCLUDE_DIR)
		SET (CMAKE_REQUIRED_INCLUDES ${GEOIP_INCLUDE_DIR})
	ENDIF (GEOIP_INCLUDE_DIR)

	CHECK_INCLUDE_FILE (GeoIP.h GEOIP_H)

	IF (GEOIP_H)
		FIND_LIBRARY (GEOIP_LIBRARY GeoIP)

		IF (NOT GEOIP_LIBRARY AND GEOIP_INCLUDE_DIR)
			FIND_LIBRARY (GEOIP_LIBRARY GeoIP
				PATHS ${GEOIP_INCLUDE_DIR}
			)
		ENDIF (NOT GEOIP_LIBRARY AND GEOIP_INCLUDE_DIR)

		IF (NOT GEOIP_LIBRARY)
			SET (ENABLE_IP2COUNTRY FALSE)
			MESSAGE (STATUS "GeoIP lib not found, disabling support")
		ELSE (NOT GEOIP_LIBRARY)
			MESSAGE (STATUS "GeoIP found useable")
		ENDIF (NOT GEOIP_LIBRARY)
	ELSE (GEOIP_H)
		SET (ENABLE_IP2COUNTRY FALSE)
		MESSAGE (STATUS "GeoIP headers not found, disabling support")
	ENDIF (GEOIP_H)

	UNSET (CMAKE_REQUIRED_INCLUDES)

	IF (GEOIP_INCLUDE_DIR)
		SET (CMAKE_REQUIRED_INCLUDES)
	ENDIF (GEOIP_INCLUDE_DIR)
ENDIF (NOT GEOIP_LIBRARY)
