IF (NOT YYENABLE_NLS)
	INCLUDE (CheckIncludeFile)

	CHECK_INCLUDE_FILE (argz.h HAVE_ARGZ_H)

	IF (NOT HAVE_ARGZ_H)
		SET (ENABLE_NLS FALSE)
	ENDIF (NOT HAVE_ARGZ_H)

	CHECK_INCLUDE_FILE (limits.h HAVE_LIMITS_H)

	IF (NOT HAVE_LIMITS_H)
		SET (ENABLE_NLS FALSE)
	ENDIF (NOT HAVE_LIMITS_H)

	CHECK_INCLUDE_FILE (locale.h HAVE_LOCALE_H)

	IF (NOT HAVE_LOCALE_H)
		SET (ENABLE_NLS FALSE)
	ENDIF (NOT HAVE_LOCALE_H)

	CHECK_INCLUDE_FILE (nl_types.h HAVE_NL_TYPES_H)

	IF (NOT HAVE_NL_TYPES_H)
		SET (ENABLE_NLS FALSE)
	ENDIF (NOT HAVE_NL_TYPES_H)

	CHECK_INCLUDE_FILE (stdlib.h HAVE_STDLIB_H)

	IF (NOT HAVE_STDLIB_H)
		SET (ENABLE_NLS FALSE)
	ENDIF (NOT HAVE_STDLIB_H)

	CHECK_INCLUDE_FILE (string.h HAVE_STRING_H)

	IF (NOT HAVE_STRING_H)
		SET (ENABLE_NLS FALSE)
	ENDIF (NOT HAVE_STRING_H)

	CHECK_INCLUDE_FILE (sys/param.h HAVE_SYS_PARAM_H)

	IF (NOT HAVE_SYS_PARAM_H)
		SET (ENABLE_NLS FALSE)
	ENDIF (NOT HAVE_SYS_PARAM_H)

	IF (NOT HAVE_STDDEF_H)
		CHECK_INCLUDE_FILE (stddef.h HAVE_STDDEF_H)
		IF (NOT HAVE_STDDEF_H)
			SET (ENABLE_NLS FALSE)
		ENDIF (NOT HAVE_STDDEF_H)
	ENDIF (NOT HAVE_STDDEF_H)

	INCLUDE (FindGettext)

	IF (NOT GETTEXT_MSGFMT_EXECUTABLE OR NOT GETTEXT_MSGMERGE_EXECUTABLE)
		SET (ENABLE_NLS FALSE)
	ENDIF (NOT GETTEXT_MSGFMT_EXECUTABLE OR NOT GETTEXT_MSGMERGE_EXECUTABLE)

	IF (ENABLE_NLS)
		MESSAGE (STATUS "Everything is fine. aMule can be localized")
		SET (YYENABLE_NLS TRUE CACHE INTERNAL "For parser, php-parser and to not recheck for nls-support" FORCE)
		ADD_SUBDIRECTORY (po)
	ELSE (ENABLE_NLS)
		MESSAGE (STATUS "You need to install GNU gettext/gettext-tools to compile aMule with i18n support.")
	ENDIF (ENABLE_NLS)
ENDIF (NOT YYENABLE_NLS)
