# Uncomment one or more of the following lines to tell cmake, where to find it's header and
# libs. You can specify the path also using -D<VAR> from commandline.

# The location, where the bison executable can be found
#SET (BISON_EXECUTABLE "${CMAKE_SOURCE_DIR}/../win_flex_bison-latest/win_bison.exe")

# The location, where to find the crypto++ header-files
#SET (BOOSTROOT "${CMAKE_SOURCE_DIR}/../boost_1_70_0")

# The location, where to find the crypto++ header-files
#SET (CRYTOPP_HEADER_PATH "${CMAKE_SOURCE_DIR}/../cryptopp")

# The location, where the linkable output of crypto++ compilation can be found.
#SET (CRYTOPP_LIB_SEARCH_PATH "${CMAKE_SOURCE_DIR}/../cryptopp/Win32/Output/Debug")

# The location, where the flex executable can be found
#SET (FLEX_EXECUTABLE "${CMAKE_SOURCE_DIR}/../win_flex_bison-latest/win_flex.exe")

# The location, where the headers of libgeoip can be found.
#SET (GEOIP_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/../geoip-api-c-master/libGeoIP")

# The location, where to find libpng headers.
#SET (PNG_HEADER_DIR "${CMAKE_SOURCE_DIR}/../lpng1626")

# The location, where to find libpng.
#SET (PNG_LIB_DIR "${CMAKE_SOURCE_DIR}/../lpng1626/projects/vstudio/Debug")

# The location, where you extracted wx-sources
#SET (wxWidgets_ROOT_DIR "${CMAKE_SOURCE_DIR}/../wxWidgets")

# The location, where to find zlib.
#SET (ZLIB_ROOT "${CMAKE_SOURCE_DIR}/../zlib-1.2.8")

IF (BISON_EXECUTABLE)
	SET (SEARCH_DIR_BISON ${BISON_EXECUTABLE})
ENDIF (BISON_EXECUTABLE)

IF (BOOST_INCLUDE_DIR)
	SET (SEARCH_DIR_BOOST ${BOOST_INCLUDE_DIR})
ENDIF (BOOST_INCLUDE_DIR)

IF (CRYTOPP_HEADER_PATH)
	SET (SEARCH_DIR_CRYPTOPP_HEADER ${CRYTOPP_HEADER_PATH})
ENDIF (CRYTOPP_HEADER_PATH)

IF (CRYTOPP_LIB_SEARCH_PATH)
	SET (SEARCH_DIR_CRYPTOPP_LIB ${CRYTOPP_LIB_SEARCH_PATH})
ENDIF (CRYTOPP_LIB_SEARCH_PATH)

IF (FLEX_EXECUTABLE)
	SET (SEARCH_DIR_FLEX ${FLEX_EXECUTABLE})
ENDIF (FLEX_EXECUTABLE)

IF (GEOIP_INCLUDE_DIR)
	SET (SEARCH_DIR_GEOIP ${GEOIP_INCLUDE_DIR})
ENDIF (GEOIP_INCLUDE_DIR)

IF (PNG_HEADER_DIR)
	SET (SEARCH_DIR_PNG_HEADER ${PNG_HEADER_DIR})
ENDIF (PNG_HEADER_DIR)

IF (PNG_LIB_DIR)
	SET (SEARCH_DIR_PNG_LIB ${PNG_LIB_DIR})
ENDIF (PNG_LIB_DIR)

IF (wxWidgets_ROOT_DIR)
	SET (SEARCH_DIR_wxWidgets ${wxWidgets_ROOT_DIR})
ENDIF (wxWidgets_ROOT_DIR)

IF (ZLIB_ROOT)
	SET (SEARCH_DIR_ZLIB ${ZLIB_ROOT})
ENDIF (ZLIB_ROOT)

SET (SEARCH_DIR_BISON ${SEARCH_DIR_BISON} CACHE FILEPATH "Location of the bison executable" FORCE)
SET (SEARCH_DIR_BOOST ${SEARCH_DIR_BOOST} CACHE PATH "Search hint for boost" FORCE)
SET (SEARCH_DIR_CRYPTOPP_HEADER ${SEARCH_DIR_CRYPTOPP_HEADER} CACHE PATH "Search hint for crypto++ headers" FORCE)
SET (SEARCH_DIR_CRYPTOPP_LIB ${SEARCH_DIR_CRYPTOPP_LIB} CACHE PATH "Search hint for crypto++ library" FORCE)
SET (SEARCH_DIR_FLEX ${SEARCH_DIR_FLEX} CACHE FILEPATH "Location of the flex executable" FORCE)
SET (SEARCH_DIR_GEOIP ${SEARCH_DIR_GEOIP} CACHE PATH "Search hint for geoip" FORCE)
SET (SEARCH_DIR_PNG_HEADER ${SEARCH_DIR_PNG_HEADER} CACHE PATH "Search hint for libpng headers" FORCE)
SET (SEARCH_DIR_PNG_LIB ${SEARCH_DIR_PNG_LIB} CACHE PATH "Search hint for libpng library" FORCE)
SET (SEARCH_DIR_UPNP ${SEARCH_DIR_UPNP} CACHE PATH "Search hint for libupnp library" FORCE)
SET (SEARCH_DIR_wxWidgets ${SEARCH_DIR_wxWidgets} CACHE PATH "Search hint for wxconfig executable" FORCE)
SET (SEARCH_DIR_ZLIB ${SEARCH_DIR_ZLIB} CACHE PATH "Search hint for zlib" FORCE)

MARK_AS_ADVANCED (FORCE SEARCH_DIR_BISON)
MARK_AS_ADVANCED (FORCE SEARCH_DIR_BOOST)
MARK_AS_ADVANCED (FORCE SEARCH_DIR_CRYPTOPP_HEADER)
MARK_AS_ADVANCED (FORCE SEARCH_DIR_CRYPTOPP_LIB)
MARK_AS_ADVANCED (FORCE SEARCH_DIR_FLEX)
MARK_AS_ADVANCED (FORCE SEARCH_DIR_GEOIP)
MARK_AS_ADVANCED (FORCE SEARCH_DIR_PNG_HEADER)
MARK_AS_ADVANCED (FORCE SEARCH_DIR_PNG_LIB)
MARK_AS_ADVANCED (FORCE SEARCH_DIR_UPNP)
MARK_AS_ADVANCED (FORCE SEARCH_DIR_wxWidgets)
MARK_AS_ADVANCED (FORCE SEARCH_DIR_ZLIB)

IF (SEARCH_DIR_BISON AND NOT BISON_EXECUTABLE)
	SET (BISON_EXECUTABLE ${SEARCH_DIR_BISON})
ENDIF (SEARCH_DIR_BISON AND NOT BISON_EXECUTABLE)

IF (SEARCH_DIR_BOOST AND NOT BOOST_INCLUDE_DIR)
	SET (BOOST_ROOT ${SEARCH_DIR_BOOST})
ENDIF (SEARCH_DIR_BOOST AND NOT BOOST_INCLUDE_DIR)

IF (SEARCH_DIR_CRYPTOPP_HEADER AND NOT CRYTOPP_HEADER_PATH)
	SET (CRYTOPP_HEADER_PATH ${SEARCH_DIR_CRYPTOPP_HEADER})
ENDIF (SEARCH_DIR_CRYPTOPP_HEADER AND NOT CRYTOPP_HEADER_PATH)

IF (SEARCH_DIR_CRYPTOPP_LIB AND NOT CRYTOPP_LIB_SEARCH_PATH)
	SET (CRYTOPP_LIB_SEARCH_PATH ${SEARCH_DIR_CRYPTOPP_LIB})
ENDIF (SEARCH_DIR_CRYPTOPP_LIB AND NOT CRYTOPP_LIB_SEARCH_PATH)

IF (SEARCH_DIR_FLEX AND NOT FLEX_EXECUTABLE)
	SET (FLEX_EXECUTABLE ${SEARCH_DIR_FLEX})
ENDIF (SEARCH_DIR_FLEX AND NOT FLEX_EXECUTABLE)

IF (SEARCH_DIR_GEOIP AND NOT GEOIP_INCLUDE_DIR)
	SET (GEOIP_INCLUDE_DIR ${SEARCH_DIR_GEOIP})
ENDIF (SEARCH_DIR_GEOIP AND NOT GEOIP_INCLUDE_DIR)

IF (SEARCH_DIR_PNG_HEADER AND NOT PNG_HEADER_DIR)
	SET (PNG_HEADER_DIR ${SEARCH_DIR_PNG_HEADER})
ENDIF (SEARCH_DIR_PNG_HEADER AND NOT PNG_HEADER_DIR)

IF (SEARCH_DIR_PNG_LIB AND NOT PNG_LIB_DIR)
	SET (PNG_LIB_DIR ${SEARCH_DIR_PNG_LIB})
ENDIF (SEARCH_DIR_PNG_LIB AND NOT PNG_LIB_DIR)

IF (SEARCH_DIR_wxWidgets AND NOT wxWidgets_ROOT_DIR)
	SET (wxWidgets_ROOT_DIR ${SEARCH_DIR_wxWidgets})
ENDIF (SEARCH_DIR_wxWidgets AND NOT wxWidgets_ROOT_DIR)

IF (SEARCH_DIR_ZLIB AND NOT ZLIB_ROOT)
	SET (ZLIB_ROOT ${SEARCH_DIR_ZLIB})
ENDIF (SEARCH_DIR_ZLIB AND NOT ZLIB_ROOT)
