INCLUDE (FindZLIB)
INCLUDE (ExternalProject)

#At least on Win32 the includepath isn't set correctly sometimes
IF (NOT EXISTS ${ZLIB_INCLUDE_DIR}/zlib.h)
	IF (EXISTS ${ZLIB_INCLUDE_DIR}/include/zlib.h)
		SET (${ZLIB_INCLUDE_DIR} ${ZLIB_INCLUDE_DIR}/include)
		MESSAGE (STATUS "zlib.h found in ${ZLIB_INCLUDE_DIR}")
	ELSE (EXISTS ${ZLIB_INCLUDE_DIR}/include/zlib.h)
		IF (NOT DOWNLOAD_AND_BUILD_DEPS)
			MESSAGE (FATAL_ERROR "No useable zlib.h found")
		ELSE (NOT DOWNLOAD_AND_BUILD_DEPS)
			SET (BUILD_ZLIB TRUE)
		ENDIF (NOT DOWNLOAD_AND_BUILD_DEPS)
	ENDIF (EXISTS ${ZLIB_INCLUDE_DIR}/include/zlib.h)
ENDIF (NOT EXISTS ${ZLIB_INCLUDE_DIR}/zlib.h)

IF (BUILD_ZLIB)
	EXTERNALPROJECT_ADD (ZLIB
		GIT_REPOSITORY https://github.com/madler/zlib.git
		GIT_TAG v1.2.11
		GIT_PROGRESS TRUE
		CONFIGURE_COMMAND ${CMAKE_COMMAND} <SOURCE_DIR> -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
		BUILD_COMMAND ${CMAKE_COMMAND} --build . --config Debug
		COMMAND ${CMAKE_COMMAND} --build . --config Release
		INSTALL_COMMAND ${CMAKE_COMMAND} --install . --config Debug
		COMMAND ${CMAKE_COMMAND} --install . --config Release
	)

	EXTERNALPROJECT_GET_PROPERTY (ZLIB INSTALL_DIR)
	LIST (APPEND EXTERNAL_DEPS ZLIB)
	SET (RECONF_COMMAND ${RECONF_COMMAND} -DZLIB_ROOT=${INSTALL_DIR})
ENDIF (BUILD_ZLIB)
