<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$text["dayabbr"]	= "g";
$text["hourabbr"]	= "h";
$text["minabbr"]	= "m";
$text["secabbr"]	= "s";
$text["runtimemsg"]	= "&#232; in funzione da";
$text["norunmsg"]	= "non &#232; in funzione";
$text["highidmsg"]	= "&#232; online (ID alto)";
$text["lowidmsg"]	= "&#232; online (ID basso)";
$text["offrunmsg"]	= "&#232; offline";
$text["amulerun"]	= "(aMule in funzione)";
$text["amulenorun"]	= "(aMule non in funzione)";
$text["sharedfiles"]	= "File condivisi";

// try to keep these next three short, otherwise the signature
// image will look messy
$text["na"]		= "N/D";
$text["rx"]		= "DL";
$text["tx"]		= "UL";

$text["queuedclients"]	= "Client in coda";
$text["transrate"]	= "kB/s";
$text["gigabytes"]	= "GB";
$text["client"]		= "Client";
$text["status"]		= "Stato";
$text["nick"]		= "Nick";
$text["localtime"]	= "Ora locale";
$text["rxspeed"]	= "Velocit&#224; DL";
$text["txspeed"]	= "Velocit&#224; UL";
$text["rxtotal"]	= "DL Totale";
$text["txtotal"]	= "UL Totale";
$text["osversion"]	= "Versione OS";
$text["hostuptime"]	= "Uptime";
$text["servername"]	= "Nome server";
$text["serveraddr"]	= "Indirizzo server:porta";
$text["ed2klink"]	= "Link ed2k";
$text["general"]	= "Generale";
$text["server"]		= "Server";
$text["signature"]	= "Firma";
$text["online"]		= "Online";
$text["offline"]	= "Offline";
$text["language"]	= "Lingua";
$text["submit"]		= "Invia";

$text["sigfileerr"]	= "Impossibile aprire il file firma";
$text["baseimgerr"]	= "Imbossibile trovare lo sfondo";
$text["iconerr"]	= "Impossibile trovare alcune icone";

?>
