<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$text["dayabbr"]	= "d";
$text["hourabbr"]	= "h";
$text["minabbr"]	= "m";
$text["secabbr"]	= "s";
$text["runtimemsg"]	= "esteve a correr durante";
$text["norunmsg"]	= "n&#227;o est&#225; a correr";
$text["highidmsg"]	= "est&#225; ligado com Alta prioridade";
$text["lowidmsg"]	= "est&#225; ligado com Baixa prioridade";
$text["offrunmsg"]	= "est&#225; desligado";
$text["amulerun"]	= "(aMule a correr)";
$text["amulenorun"]	= "(aMule parado)";
$text["sharedfiles"]	= "Ficheiros Partilhados";

// Kad
$text["kadonmsg"]       = "( Kad: Ligado )";
$text["kadfwmsg"]       = "( Kad: Protegido)";
$text["kadoffmsg"]      = "( Kad: Desligado )";
$text["kadstatus"]      = "Estado Kad";
$text["kadfw"]          = "Protegido";
$text["kadon"]          = "Ligado";
$text["kadoff"]         = "Desligado";
// try to keep these next three short, otherwise the signature
// image will look messy
$text["na"]		= "N/A";
$text["rx"]		= "RX";
$text["tx"]		= "TX";

$text["queuedclients"]	= "Clientes em espera";
$text["transrate"]	= "kB/s";
$text["gigabytes"]	= "GB";
$text["client"]		= "Cliente";
$text["ed2kstatus"]	= "Estado";
$text["nick"]		= "Nick";
$text["localtime"]	= "Tempo local";
$text["rxspeed"]	= "Taxa recep&#231;&#227;o";
$text["txspeed"]	= "Taxa envio";
$text["rxtotal"]	= "Total recebido";
$text["txtotal"]	= "Total enviado";
$text["osversion"]	= "vers&#227;o Sist.Op.";
$text["hostuptime"]	= "Tempo ligado";
$text["servername"]	= "Nome do Servidor";
$text["serveraddr"]	= "Servidor endere&#231;o:porto";
$text["ed2klink"]	= "link ED2K";
$text["general"]	= "Geral";
$text["server"]		= "Servidor";
$text["signature"]	= "Assinatura";
$text["online"]		= "Ligado";
$text["offline"]	= "Desligado";
$text["language"]	= "Linguagem";
$text["submit"]		= "Enviar";

$text["sigfileerr"]	= "Impossibilidade de abertura do ficheiro de assinaturas";
$text["baseimgerr"]	= "Imagem de base n&#227;o encontrada";
$text["iconerr"]	= "Um ou mais icons n&#227;o encontrados";

?>
