<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$text["dayabbr"]	= "d";
$text["hourabbr"]	= "h";
$text["minabbr"]	= "m";
$text["secabbr"]	= "s";
$text["runtimemsg"]	= "lleva funcionando";
$text["norunmsg"]	= "no est&#225; funcionando";
$text["highidmsg"]	= "est&#225; conectado (id alta)";
$text["lowidmsg"]	= "est&#225; conectado (id baja)";
$text["offrunmsg"]	= "est&#225; desconectado";
$text["connmsg"]	= "est&#225; conectando";
$text["amulerun"]	= "(aMule est&#225; ejecut&#225;ndose)";
$text["amulenorun"]	= "(aMule no est&#225; ejecut&#225;ndose)";
$text["sharedfiles"]	= "Archivos compartidos";
$text["na"]		= "N/D";
$text["rx"]		= "RX";
$text["tx"]		= "TX";
$text["queuedclients"]	= "Clientes en cola";
$text["transrate"]	= "kB/s";
$text["gigabytes"]	= "GB";
$text["client"]		= "Cliente";
$text["status"]		= "Estado";
$text["nick"]		= "Nick";
$text["localtime"]	= "Hora local";
$text["rxspeed"]	= "Velocidad RX";
$text["txspeed"]	= "Velocidad TX";
$text["rxtotal"]	= "Total RX";
$text["txtotal"]	= "Total TX";
$text["osversion"]	= "Versi&#243;n SO";
$text["hostuptime"]	= "Tiempo de ejecuci&#243;n del host";
$text["servername"]	= "Nombre del servidor";
$text["serveraddr"]	= "Direcci&#243;n del servidor:puerto";
$text["ed2klink"]	= "Enlace ED2K";
$text["general"]	= "General";
$text["server"]		= "Servidor";
$text["signature"]	= "Firma";
$text["connecting"]	= "Conectando";
$text["online"]		= "Conectado";
$text["offline"]	= "Desconectado";
$text["language"]	= "Idioma";
$text["submit"]		= "Enviar";

$text["sigfileerr"]	= "Imposible abrir el archivo de firma";
$text["baseimgerr"]	= "Imposible encontrar la im&#225;gen base";
$text["iconerr"]	= "Imposible encontrar uno o m&#225;s iconos";

?>
