<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$text["dayabbr"]	= "n";
$text["hourabbr"]	= "&#243;";
$text["minabbr"]	= "p";
$text["secabbr"]	= "mp";
$text["runtimemsg"]	= "futott";
$text["norunmsg"]	= "nem fut";
$text["connmsg"]	= "kapcsol&#243;d&#225;s folyamatban";
$text["highidmsg"]	= "online (high id)";
$text["lowidmsg"]	= "online (low id)";
$text["offrunmsg"]	= "offline";
$text["amulerun"]	= "(aMule fut)";
$text["amulenorun"]	= "(aMule nem fut)";
$text["sharedfiles"]	= "Megosztott f&#225;jlok";

// try to keep these next three short, otherwise the signature
// image will look messy
$text["na"]		= "N/A";
$text["rx"]		= "RX";
$text["tx"]		= "TX";

$text["queuedclients"]	= "V&#225;rakoz&#243; kliensek";
$text["transrate"]	= "kB/s";
$text["gigabytes"]	= "GB";
$text["client"]		= "Kliens";
$text["status"]		= "&#193;llapot";
$text["nick"]		= "Nick";
$text["localtime"]	= "Helyi id&#245;";
$text["rxspeed"]	= "RX sebess&#233;g";
$text["txspeed"]	= "TX sebess&#233;g";
$text["rxtotal"]	= "RX &#246sszesen";
$text["txtotal"]	= "TX &#246sszesen";
$text["osversion"]	= "OS verzi&#243;";
$text["hostuptime"]	= "Host m&#251;k&#246d&#233;si ideje";
$text["servername"]	= "Kiszolg&#225;l&#243; n&#233;v";
$text["serveraddr"]	= "Kiszolg&#225;l&#243; címe:portja";
$text["ed2klink"]	= "ED2K link";
$text["general"]	= "&#193;ltal&#225;nos";
$text["server"]		= "Kiszolg&#225;l&#243;";
$text["signature"]	= "&#193;l&#225;ír&#225;s";
$text["connecting"]	= "Kapcsol&#243;d&#225;s";
$text["online"]		= "Online";
$text["offline"]	= "Offline";
$text["language"]	= "Nyelv";
$text["submit"]		= "V&#233;grehajt";

$text["sigfileerr"]	= "Al&#225;ír&#225;s f&#225;jlt nem lehet megnyitni";
$text["baseimgerr"]	= "Nem tal&#225;lhat&#243; alapk&#233;p";
$text["iconerr"]	= "Nem tal&#225;lhat&#243; egy vagy t&#246bb ikon";

?>
