<?php

/**
 * AMPS - AMule PHP Statistics
 * Written by überpenguin, AMPS is an adaptation of BigBob's aStats
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

$text["dayabbr"]	= "d";
$text["hourabbr"]	= "u";
$text["minabbr"]	= "m";
$text["secabbr"]	= "s";
$text["runtimemsg"]	= "draait";
$text["norunmsg"]	= "draait niet";
$text["connmsg"]	= "is aan het verbinden";
$text["highidmsg"]	= "is online (high id)";
$text["lowidmsg"]	= "is online (low id)";
$text["offrunmsg"]	= "is offline";
$text["amulerun"]	= "(aMule draait)";
$text["amulenorun"]	= "(aMule draait niet)";
$text["sharedfiles"]	= "Gedeelde bestanden";
$text["na"]		= "N/B";
$text["rx"]		= "RX";
$text["tx"]		= "TX";
$text["queuedclients"]	= "Clients in wachtrij";
$text["transrate"]	= "kB/s";
$text["gigabytes"]	= "GB";
$text["client"]		= "Client";
$text["status"]		= "Status";
$text["nick"]		= "Nick";
$text["localtime"]	= "Lokale tijd";
$text["rxspeed"]	= "RX snelheid";
$text["txspeed"]	= "TX snelheid";
$text["rxtotal"]	= "RX totaal";
$text["txtotal"]	= "TX totaal";
$text["osversion"]	= "OS versie";
$text["hostuptime"]	= "Host uptime";
$text["servername"]	= "Server naam";
$text["serveraddr"]	= "Server adres:poort";
$text["ed2klink"]	= "ED2K link";
$text["general"]	= "Algemeen";
$text["server"]		= "Server";
$text["signature"]	= "Handtekening";
$text["connecting"]	= "Aan het Verbinden";
$text["online"]		= "Online";
$text["offline"]	= "Offline";
$text["language"]	= "Taal";
$text["submit"]		= "Verstuur";

$text["sigfileerr"]	= "Kon handtekening bestand niet openen";
$text["baseimgerr"]	= "Kan basis afbeelding niet vinden";
$text["iconerr"]	= "Kan een of meer pictogrammen niet vinden";

?>
