.TH CAS 1 "March 2005" "cas v0.5" "aMule utilities"
.SH NAME
cas \- c aMule statistics
.SH SYNOPSIS
.B cas
.RI [ OPTIONS ]
.SH DESCRIPTION
.PP
    ___    _ _   ___    c aMule statistics
  /'___) /'_` )/',__)   by Pedro de Oliveira
 ( (___ ( (_| |\\\__, \\   <falso@rdk.homeip.net>
 `\\____)`\\__,_)(____/   Version 0.5
.P
\fBcas\fR is a program for displaying the contents of your aMule online
signature file to console (in a human readable form).
.SS OPTIONS:
.TP
\fB\-o\fR, \fB\-\-picture\fR, \fB\-P\fR
Writes the online signature picture.
You can optionally append \fI\=\<PATH\>\fR to this option, to specify where the picture should be written
.TP
\fB\-p\fR, \fB\-\-html\fR, \fB\-H\fR
HTML page with stats and picture.
You can optionally append \fI\=\<PATH\>\fR to this option, to specify where the page should be written
.TP
\fB\-c\fR, \fB\-\-config\-dir\fR
Specifies a config-dir different from home
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints a short usage description.
.P
Without any options, prints online signature data to stdout.
.SH FILES
~/.aMule/casrc
.br
stat.png
.br
tmp.html
.SH AUTHOR
\fBcas\fR was written by Pedro de Oliveira <falso@rdk.homeip.net>
.SH REPORTING BUGS
Please report bugs either on our forum (\fIhttp://forum.amule.org/\fR), or in our bugtracker (\fIhttp://bugs.amule.org/\fR).
Please do not report bugs in e-mail, neither to our mailing list nor directly to any team member.
.SH COPYRIGHT
aMule and all of its related utilities are distributed under the GNU General Public License.
.SH SEE ALSO
\fBamule\fR(1), \fBwxcas\fR(1)
