.TH ALC 1 "2005 március" "aLinkCreator" "aMule segédprogramok"
.SH NÉV
aLinkCreator \- az aMule ED2k hivatkozás készítõ
.SH ÁTTEKINTÉS
.B alc
.SH LEÍRÁS
Az \fBalc\fR egy grafikus segédeszköz ED2k hivatkozások készítéséhez bármely fájlhoz a számítógépen.
.SH HIBÁK JELENTÉSE
A hibákat kérjük vagy a fórumon (\fIhttp://forum.amule.org/\fR), vagy a hibakövetõben (\fIhttp://bugs.amule.org/\fR) jelentsék.
Hibákról kérjük ne írjanak levelet (e-mail-t) se a levelzési listára, se közvetlenül valamelyik fejlesztõnek.
.SH COPYRIGHT
Az aMule és az összes hozzá tartozó segédprogram a GNU General Public Licence védelme alatt áll.
.SH LÁSD MÉG
\fBalcc\fR(1), \fBamule\fR(1)
.SH MAGYAR FORDÍTÁS
Dévai Tamás <gonosztopi@amule.org>
