.TH XAS 1
.SH NAME
xas \- X\-Chat aMule Statistics
.SH SYNOPSIS
.B none
.SH DESCRIPTION
.B xas
is a plugin for xchat. For loading see your xchat documentation. After loading 
type /xas and it will send statistics to the channel you are in. These 
are taken from your Online Signature file.
.SH AUTHOR
This manpage was written by Vollstrecker <amule@vollstreckernet.de> 
.SH SEE ALSO
\fBamule\fR(1)
