.TH AMULE 1
.SH NAME
cas
.SH SYNOPSIS
.B cas
.SH "DESCRIPTION"
.B cas
c aMule statistics is a program for displaying the contents of your 
online-signature-file to console.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH AUTHOR
cas was written by Pedro de Oliveira <falso@rdk.homeip.net>
This manpage was written by Vollstrecker for Debian <amule@vollstreckernet.de> 

