.TH AMULE 1
.SH NAME
wxcas
.SH SYNOPSIS
.B wxcas
.SH "DESCRIPTION"
.B wxcas
wx c aMule statistics is a program for displaying the contents of your 
online-signature-file in a nice wx Window on your Desktop.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH AUTHOR
wxcas was written by ThePolish <thepolish@vipmail.ru>
This manpage was written by Vollstrecker for Debian <amule@vollstreckernet.de> 

