.TH AMULE 1
.SH NAME
xas
.SH SYNTAX
.B keine
.SH "Beschreibung"
.B xas
ist ein Plugin für XChat. Wie man es lädt ist dessen Doku zu entnehmen. 
Nach dem Laden tippe einfach /xas, und es werden Statistiken über dein 
Amule an den Channel in dem du dich befindest gesendet. Diese werden 
aus deiner Online-Signatur-Datei gelesen.
.PP
Die ManPage wurde für Debian GNU/Linux geschrieben, da das 
Originalprogramm keine enthält.

.SH AUTHOR
aMule wurde geschrieben von Stephane Colin <bigbog@tiscali.fr>
Diese ManPage wurde für Debian geschrieben von Vollstrecker <amule@vollstreckernet.de> 

