.TH AMULE 1
.SH NAME
xas
.SH SYNOPSIS
.B none
.SH "DESCRIPTION"
.B xas
is a plugin for xchat. For loading see your xchat Docs. After loading 
type /xas and it will send statistics to the channel you are in. These 
are taken from you Online-Signaturefile.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH AUTHOR
aMule was written by Stephane Colin <bigbog@tiscali.fr>
This manpage was written by Vollstrecker for Debian <amule@vollstreckernet.de> 

